// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScrAlbumShow = NULL;
lv_obj_t * ui_ScrAlbumShow_ContMain = NULL;
lv_obj_t * ui_ScrAlbumShow_ContHeader = NULL;
lv_obj_t * ui_ScrAlbumShow_BtnExit = NULL;
lv_obj_t * ui_ScrAlbumShow_LabelExit = NULL;
lv_obj_t * ui_ScrAlbumShow_LabelTitle = NULL;
lv_obj_t * ui_ScrAlbumShow_BtnInfo = NULL;
lv_obj_t * ui_ScrAlbumShow_LabelInfo = NULL;
lv_obj_t * ui_ScrAlbumShow_ContShowInfo = NULL;
lv_obj_t * ui_ScrAlbumShow_LabelShowInfo = NULL;
// event funtions
void ui_event_ScrAlbumShow_BtnExit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrAlbum,&ui_ScrAlbumShow,LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrAlbum_screen_init);
    }
}

void ui_event_ScrAlbumShow_BtnInfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED)
    {
        albumHandle.isShowInfo++; /*因为这个变量只占一位，所以只能0,1变换*/
        if (albumHandle.isShowInfo == 1) lv_label_set_text(ui_ScrAlbumShow_LabelInfo, LV_SYMBOL_EYE_CLOSE);
        else
        {
            lv_label_set_text(ui_ScrAlbumShow_LabelInfo, LV_SYMBOL_EYE_OPEN);
            albumHandle.isDispImg = 1; /*关闭显示面板后一定要再显示下图片，不然显示面板那块就是白的*/
        }

        _ui_flag_modify(ui_ScrAlbumShow_ContShowInfo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}


/*屏幕事件*/
void ui_event_ScrAlbumShow(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE)
    {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act()); /*获取手势方向*/
        //if (dir == LV_DIR_NONE) return;
        if (dir == LV_DIR_RIGHT)
        {
            printf("right\n");
            albumHandle.isSwipeRight = 1;
        }
        else if (dir == LV_DIR_LEFT)
        {
            printf("left\n");
            albumHandle.isSwipeLeft = 1;
        }
    }
}
// build funtions

void ui_ScrAlbumShow_screen_init(void)
{
    ui_ScrAlbumShow = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrAlbumShow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_ScrAlbumShow, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_ScrAlbumShow_screen_destroy);

    ui_ScrAlbumShow_ContMain = lv_obj_create(ui_ScrAlbumShow);
    lv_obj_remove_style_all(ui_ScrAlbumShow_ContMain);
    lv_obj_set_width(ui_ScrAlbumShow_ContMain, lv_pct(100));
    lv_obj_set_height(ui_ScrAlbumShow_ContMain, lv_pct(100));
    lv_obj_remove_flag(ui_ScrAlbumShow_ContMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrAlbumShow_ContHeader = lv_obj_create(ui_ScrAlbumShow_ContMain);
    lv_obj_remove_style_all(ui_ScrAlbumShow_ContHeader);
    lv_obj_set_width(ui_ScrAlbumShow_ContHeader, lv_pct(100));
    lv_obj_set_height(ui_ScrAlbumShow_ContHeader, lv_pct(10));
    lv_obj_remove_flag(ui_ScrAlbumShow_ContHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ScrAlbumShow_ContHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrAlbumShow_ContHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrAlbumShow_ContHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScrAlbumShow_ContHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAlbumShow_BtnExit = lv_button_create(ui_ScrAlbumShow_ContHeader);
    lv_obj_set_width(ui_ScrAlbumShow_BtnExit, lv_pct(15));
    lv_obj_set_height(ui_ScrAlbumShow_BtnExit, lv_pct(100));
    lv_obj_set_x(ui_ScrAlbumShow_BtnExit, lv_pct(2));
    lv_obj_set_y(ui_ScrAlbumShow_BtnExit, lv_pct(0));
    lv_obj_add_flag(ui_ScrAlbumShow_BtnExit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrAlbumShow_BtnExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrAlbumShow_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrAlbumShow_BtnExit, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrAlbumShow_BtnExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrAlbumShow_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrAlbumShow_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAlbumShow_LabelExit = lv_label_create(ui_ScrAlbumShow_BtnExit);
    lv_obj_set_width(ui_ScrAlbumShow_LabelExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrAlbumShow_LabelExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrAlbumShow_LabelExit, lv_pct(2));
    lv_obj_set_y(ui_ScrAlbumShow_LabelExit, lv_pct(0));
    lv_obj_set_align(ui_ScrAlbumShow_LabelExit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrAlbumShow_LabelExit, LV_SYMBOL_LEFT);
    lv_obj_set_style_text_color(ui_ScrAlbumShow_LabelExit, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrAlbumShow_LabelExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrAlbumShow_LabelExit, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAlbumShow_LabelTitle = lv_label_create(ui_ScrAlbumShow_ContHeader);
    lv_obj_set_width(ui_ScrAlbumShow_LabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrAlbumShow_LabelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrAlbumShow_LabelTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrAlbumShow_LabelTitle, "baizi.bjpg");
    lv_obj_set_style_text_font(ui_ScrAlbumShow_LabelTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAlbumShow_BtnInfo = lv_button_create(ui_ScrAlbumShow_ContHeader);
    lv_obj_set_width(ui_ScrAlbumShow_BtnInfo, lv_pct(15));
    lv_obj_set_height(ui_ScrAlbumShow_BtnInfo, lv_pct(100));
    lv_obj_set_x(ui_ScrAlbumShow_BtnInfo, lv_pct(-2));
    lv_obj_set_y(ui_ScrAlbumShow_BtnInfo, lv_pct(0));
    lv_obj_set_align(ui_ScrAlbumShow_BtnInfo, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ScrAlbumShow_BtnInfo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrAlbumShow_BtnInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrAlbumShow_BtnInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrAlbumShow_BtnInfo, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrAlbumShow_BtnInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrAlbumShow_BtnInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrAlbumShow_BtnInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAlbumShow_LabelInfo = lv_label_create(ui_ScrAlbumShow_BtnInfo);
    lv_obj_set_width(ui_ScrAlbumShow_LabelInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrAlbumShow_LabelInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrAlbumShow_LabelInfo, lv_pct(2));
    lv_obj_set_y(ui_ScrAlbumShow_LabelInfo, lv_pct(0));
    lv_obj_set_align(ui_ScrAlbumShow_LabelInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrAlbumShow_LabelInfo, LV_SYMBOL_EYE_OPEN);
    lv_obj_set_style_text_color(ui_ScrAlbumShow_LabelInfo, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrAlbumShow_LabelInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrAlbumShow_LabelInfo, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAlbumShow_ContShowInfo = lv_obj_create(ui_ScrAlbumShow);
    lv_obj_remove_style_all(ui_ScrAlbumShow_ContShowInfo);
    lv_obj_set_width(ui_ScrAlbumShow_ContShowInfo, lv_pct(90));
    lv_obj_set_height(ui_ScrAlbumShow_ContShowInfo, lv_pct(40));
    lv_obj_set_x(ui_ScrAlbumShow_ContShowInfo, lv_pct(0));
    lv_obj_set_y(ui_ScrAlbumShow_ContShowInfo, lv_pct(20));
    lv_obj_set_align(ui_ScrAlbumShow_ContShowInfo, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ScrAlbumShow_ContShowInfo, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ScrAlbumShow_ContShowInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrAlbumShow_ContShowInfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrAlbumShow_ContShowInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrAlbumShow_ContShowInfo, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAlbumShow_LabelShowInfo = lv_label_create(ui_ScrAlbumShow_ContShowInfo);
    lv_obj_set_width(ui_ScrAlbumShow_LabelShowInfo, lv_pct(90));
    lv_obj_set_height(ui_ScrAlbumShow_LabelShowInfo, lv_pct(80));
    lv_obj_set_align(ui_ScrAlbumShow_LabelShowInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrAlbumShow_LabelShowInfo,
                      "file name: baizi.bjpg\nfile resolution: 240 X 240\nfile size: 100.2KB");

    lv_obj_add_event_cb(ui_ScrAlbumShow_BtnExit, ui_event_ScrAlbumShow_BtnExit, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrAlbumShow_BtnInfo, ui_event_ScrAlbumShow_BtnInfo, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_ScrAlbumShow, ui_event_ScrAlbumShow, LV_EVENT_ALL, NULL);
}

void ui_ScrAlbumShow_screen_destroy(void)
{
    if(ui_ScrAlbumShow) lv_obj_del(ui_ScrAlbumShow);

    // NULL screen variables
    ui_ScrAlbumShow = NULL;
    ui_ScrAlbumShow_ContMain = NULL;
    ui_ScrAlbumShow_ContHeader = NULL;
    ui_ScrAlbumShow_BtnExit = NULL;
    ui_ScrAlbumShow_LabelExit = NULL;
    ui_ScrAlbumShow_LabelTitle = NULL;
    ui_ScrAlbumShow_BtnInfo = NULL;
    ui_ScrAlbumShow_LabelInfo = NULL;
    ui_ScrAlbumShow_ContShowInfo = NULL;
    ui_ScrAlbumShow_LabelShowInfo = NULL;

}

void ui_ScrAlbumShow_screen_relocalize(void)
{
    // label widgets on screen

}
