// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScrVedioShow = NULL;
lv_obj_t * ui_ScrVedioShow_ContMain = NULL;
lv_obj_t * ui_ScrVedioShow_ContHeader = NULL;
lv_obj_t * ui_ScrVedioShow_BtnExit = NULL;
lv_obj_t * ui_ScrVedioShow_LabelExit = NULL;
lv_obj_t * ui_ScrVedioShow_LabelTitle = NULL;
lv_obj_t * ui_ScrVedioShow_ContFooter = NULL;
lv_obj_t * ui_ScrVedioShow_ContPlayCtl = NULL;
lv_obj_t * ui_ScrVedioShow_BtnPrev = NULL;
lv_obj_t * ui_ScrVedioShow_LabelPrev = NULL;
lv_obj_t * ui_ScrVedioShow_BtnPlay = NULL;
lv_obj_t * ui_ScrVedioShow_LabelPlay = NULL;
lv_obj_t * ui_ScrVedioShow_BtnNext = NULL;
lv_obj_t * ui_ScrVedioShow_LabelNext = NULL;
lv_obj_t * ui_ScrVedioShow_Slider = NULL;
lv_obj_t * ui_ScrVedioShow_ContVolume = NULL;
lv_obj_t * ui_ScrVedioShow_BarVolume = NULL;
lv_obj_t * ui_ScrVedioShow_LabelVolSymbol = NULL;

// event funtions
void ui_event_ScrVedioShow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_GESTURE)
    {
        printf("gesture start\n");
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_active());
        if (dir == LV_DIR_TOP || dir== LV_DIR_BOTTOM)
        {
            scr_vedio_show_eh(e);
        }
    }
}


void ui_event_ScrVedioShow_ContMain(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_RELEASED)
    {
        printf("released\n");
        scr_vedio_show_cont_main_eh(e);
    }
    else if (event_code == LV_EVENT_PRESSING)
    {
        scr_vedio_show_cont_main_eh2(e);
    }
    else if (event_code == LV_EVENT_SHORT_CLICKED)
    {
        _ui_flag_modify(ui_ScrVedioShow_ContFooter, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_ScrVedioShow_ContHeader, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}


void ui_event_ScrVedioShow_BtnExit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) 
    {
        vedioHandle.isExitVedio=1;
        Vedio_SetShowDir(0);
        _ui_screen_change(&ui_ScrVedio,&ui_ScrVedioShow,LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrVedio_screen_init);
    }
}

void ui_event_ScrVedioShow_BtnPrev(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scr_vedio_show_btn_prev_eh(e);
    }
}

void ui_event_ScrVedioShow_BtnPlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scr_vedio_show_btn_play_eh(e);
    }
}

void ui_event_ScrVedioShow_BtnNext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scr_vedio_show_btn_next_eh(e);
    }
}

void ui_event_ScrVedioShow_Slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        scr_vedio_show_slider_eh(e);
    }
}

// build funtions

void ui_ScrVedioShow_screen_init(void)
{
    ui_ScrVedioShow = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrVedioShow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_ScrVedioShow, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_ScrVedioShow_screen_destroy);
    // lv_obj_set_size(ui_ScrVedioShow,LCD_GetWidth(),LCD_GetHeight());

    ui_ScrVedioShow_ContMain = lv_obj_create(ui_ScrVedioShow);
    lv_obj_remove_style_all(ui_ScrVedioShow_ContMain);
    lv_obj_set_width(ui_ScrVedioShow_ContMain, lv_pct(100));
    lv_obj_set_height(ui_ScrVedioShow_ContMain, lv_pct(100));
    lv_obj_add_flag(ui_ScrVedioShow_ContMain, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_ScrVedioShow_ContMain,LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrVedioShow_ContMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrVedioShow_ContMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedioShow_ContHeader = lv_obj_create(ui_ScrVedioShow_ContMain);
    lv_obj_remove_style_all(ui_ScrVedioShow_ContHeader);
    lv_obj_set_width(ui_ScrVedioShow_ContHeader, lv_pct(100));
    lv_obj_set_height(ui_ScrVedioShow_ContHeader, lv_pct(9));
    lv_obj_add_flag(ui_ScrVedioShow_ContHeader, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ScrVedioShow_ContHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrVedioShow_ContHeader, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrVedioShow_ContHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedioShow_BtnExit = lv_button_create(ui_ScrVedioShow_ContHeader);
    lv_obj_set_width(ui_ScrVedioShow_BtnExit, lv_pct(15));
    lv_obj_set_height(ui_ScrVedioShow_BtnExit, lv_pct(100));
    lv_obj_set_x(ui_ScrVedioShow_BtnExit, lv_pct(2));
    lv_obj_set_y(ui_ScrVedioShow_BtnExit, lv_pct(0));
    lv_obj_add_flag(ui_ScrVedioShow_BtnExit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrVedioShow_BtnExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrVedioShow_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrVedioShow_BtnExit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrVedioShow_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrVedioShow_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrVedioShow_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedioShow_LabelExit = lv_label_create(ui_ScrVedioShow_BtnExit);
    lv_obj_set_width(ui_ScrVedioShow_LabelExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrVedioShow_LabelExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrVedioShow_LabelExit, lv_pct(2));
    lv_obj_set_y(ui_ScrVedioShow_LabelExit, lv_pct(0));
    lv_obj_set_align(ui_ScrVedioShow_LabelExit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrVedioShow_LabelExit, LV_SYMBOL_LEFT);
    lv_obj_set_style_text_color(ui_ScrVedioShow_LabelExit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrVedioShow_LabelExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrVedioShow_LabelExit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedioShow_LabelTitle = lv_label_create(ui_ScrVedioShow_ContHeader);
    lv_obj_set_width(ui_ScrVedioShow_LabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrVedioShow_LabelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrVedioShow_LabelTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrVedioShow_LabelTitle, "test.bmp4");
    lv_obj_set_style_text_color(ui_ScrVedioShow_LabelTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrVedioShow_LabelTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrVedioShow_LabelTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedioShow_ContFooter = lv_obj_create(ui_ScrVedioShow_ContMain);
    lv_obj_remove_style_all(ui_ScrVedioShow_ContFooter);
    lv_obj_set_width(ui_ScrVedioShow_ContFooter, lv_pct(100));
    lv_obj_set_height(ui_ScrVedioShow_ContFooter, lv_pct(10));
    lv_obj_set_x(ui_ScrVedioShow_ContFooter, lv_pct(0));
    lv_obj_set_y(ui_ScrVedioShow_ContFooter, lv_pct(-4));
    lv_obj_set_align(ui_ScrVedioShow_ContFooter, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ScrVedioShow_ContFooter, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ScrVedioShow_ContFooter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrVedioShow_ContFooter, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrVedioShow_ContFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedioShow_ContPlayCtl = lv_obj_create(ui_ScrVedioShow_ContFooter);
    lv_obj_remove_style_all(ui_ScrVedioShow_ContPlayCtl);
    lv_obj_set_width(ui_ScrVedioShow_ContPlayCtl, lv_pct(30));
    lv_obj_set_height(ui_ScrVedioShow_ContPlayCtl, lv_pct(100));
    lv_obj_set_align(ui_ScrVedioShow_ContPlayCtl, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_ScrVedioShow_ContPlayCtl, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrVedioShow_BtnPrev = lv_button_create(ui_ScrVedioShow_ContPlayCtl);
    lv_obj_set_width(ui_ScrVedioShow_BtnPrev, lv_pct(30));
    lv_obj_set_height(ui_ScrVedioShow_BtnPrev, lv_pct(100));
    lv_obj_add_flag(ui_ScrVedioShow_BtnPrev, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrVedioShow_BtnPrev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrVedioShow_BtnPrev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrVedioShow_BtnPrev, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrVedioShow_BtnPrev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrVedioShow_BtnPrev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrVedioShow_BtnPrev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedioShow_LabelPrev = lv_label_create(ui_ScrVedioShow_BtnPrev);
    lv_obj_set_width(ui_ScrVedioShow_LabelPrev, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrVedioShow_LabelPrev, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrVedioShow_LabelPrev, lv_pct(2));
    lv_obj_set_y(ui_ScrVedioShow_LabelPrev, lv_pct(0));
    lv_obj_set_align(ui_ScrVedioShow_LabelPrev, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrVedioShow_LabelPrev, LV_SYMBOL_PREV);
    lv_obj_set_style_text_color(ui_ScrVedioShow_LabelPrev, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrVedioShow_LabelPrev, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrVedioShow_LabelPrev, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedioShow_BtnPlay = lv_button_create(ui_ScrVedioShow_ContPlayCtl);
    lv_obj_set_width(ui_ScrVedioShow_BtnPlay, lv_pct(30));
    lv_obj_set_height(ui_ScrVedioShow_BtnPlay, lv_pct(100));
    lv_obj_set_align(ui_ScrVedioShow_BtnPlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScrVedioShow_BtnPlay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrVedioShow_BtnPlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrVedioShow_BtnPlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrVedioShow_BtnPlay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrVedioShow_BtnPlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrVedioShow_BtnPlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrVedioShow_BtnPlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedioShow_LabelPlay = lv_label_create(ui_ScrVedioShow_BtnPlay);
    lv_obj_set_width(ui_ScrVedioShow_LabelPlay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrVedioShow_LabelPlay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrVedioShow_LabelPlay, lv_pct(2));
    lv_obj_set_y(ui_ScrVedioShow_LabelPlay, lv_pct(0));
    lv_obj_set_align(ui_ScrVedioShow_LabelPlay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrVedioShow_LabelPlay,LV_SYMBOL_PAUSE);
    lv_obj_set_style_text_color(ui_ScrVedioShow_LabelPlay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrVedioShow_LabelPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrVedioShow_LabelPlay, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedioShow_BtnNext = lv_button_create(ui_ScrVedioShow_ContPlayCtl);
    lv_obj_set_width(ui_ScrVedioShow_BtnNext, lv_pct(30));
    lv_obj_set_height(ui_ScrVedioShow_BtnNext, lv_pct(100));
    lv_obj_set_align(ui_ScrVedioShow_BtnNext, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ScrVedioShow_BtnNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrVedioShow_BtnNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrVedioShow_BtnNext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrVedioShow_BtnNext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrVedioShow_BtnNext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrVedioShow_BtnNext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrVedioShow_BtnNext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedioShow_LabelNext = lv_label_create(ui_ScrVedioShow_BtnNext);
    lv_obj_set_width(ui_ScrVedioShow_LabelNext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrVedioShow_LabelNext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrVedioShow_LabelNext, lv_pct(2));
    lv_obj_set_y(ui_ScrVedioShow_LabelNext, lv_pct(0));
    lv_obj_set_align(ui_ScrVedioShow_LabelNext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrVedioShow_LabelNext,LV_SYMBOL_NEXT);
    lv_obj_set_style_text_color(ui_ScrVedioShow_LabelNext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrVedioShow_LabelNext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrVedioShow_LabelNext, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedioShow_Slider = lv_slider_create(ui_ScrVedioShow_ContFooter);
    lv_slider_set_value(ui_ScrVedioShow_Slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ScrVedioShow_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_ScrVedioShow_Slider,
                                                                                                        0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ScrVedioShow_Slider, lv_pct(60));
    lv_obj_set_height(ui_ScrVedioShow_Slider, lv_pct(15));
    lv_obj_set_x(ui_ScrVedioShow_Slider, lv_pct(-5));
    lv_obj_set_y(ui_ScrVedioShow_Slider, lv_pct(0));
    lv_obj_set_align(ui_ScrVedioShow_Slider, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_ScrVedioShow_Slider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrVedioShow_Slider, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ScrVedioShow_Slider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrVedioShow_Slider, lv_color_hex(0xFF9D9D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrVedioShow_Slider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ScrVedioShow_Slider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrVedioShow_Slider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ScrVedioShow_Slider,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ScrVedioShow_Slider, lv_obj_get_style_pad_right(ui_ScrVedioShow_Slider,
                                                                                LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ScrVedioShow_ContVolume = lv_obj_create(ui_ScrVedioShow_ContMain);
    lv_obj_remove_style_all(ui_ScrVedioShow_ContVolume);
    lv_obj_set_width(ui_ScrVedioShow_ContVolume, lv_pct(40));
    lv_obj_set_height(ui_ScrVedioShow_ContVolume, lv_pct(10));
    lv_obj_set_align(ui_ScrVedioShow_ContVolume, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScrVedioShow_ContVolume, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ScrVedioShow_ContVolume, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrVedioShow_ContVolume, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrVedioShow_ContVolume, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrVedioShow_ContVolume, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedioShow_BarVolume = lv_bar_create(ui_ScrVedioShow_ContVolume);
    lv_bar_set_value(ui_ScrVedioShow_BarVolume, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_ScrVedioShow_BarVolume, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ScrVedioShow_BarVolume, lv_pct(60));
    lv_obj_set_height(ui_ScrVedioShow_BarVolume, lv_pct(10));
    lv_obj_set_x(ui_ScrVedioShow_BarVolume, lv_pct(-10));
    lv_obj_set_y(ui_ScrVedioShow_BarVolume, lv_pct(0));
    lv_obj_set_align(ui_ScrVedioShow_BarVolume, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_radius(ui_ScrVedioShow_BarVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrVedioShow_BarVolume, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrVedioShow_BarVolume, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ScrVedioShow_BarVolume, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrVedioShow_BarVolume, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrVedioShow_BarVolume, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ScrVedioShow_BarVolume,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ScrVedioShow_BarVolume,
                                                                                lv_obj_get_style_pad_right(ui_ScrVedioShow_BarVolume, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ScrVedioShow_LabelVolSymbol = lv_label_create(ui_ScrVedioShow_ContVolume);
    lv_obj_set_width(ui_ScrVedioShow_LabelVolSymbol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrVedioShow_LabelVolSymbol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrVedioShow_LabelVolSymbol, lv_pct(10));
    lv_obj_set_y(ui_ScrVedioShow_LabelVolSymbol, lv_pct(0));
    lv_obj_set_align(ui_ScrVedioShow_LabelVolSymbol, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ScrVedioShow_LabelVolSymbol, LV_SYMBOL_AUDIO);
    lv_obj_set_style_text_color(ui_ScrVedioShow_LabelVolSymbol, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrVedioShow_LabelVolSymbol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrVedioShow_LabelVolSymbol, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScrVedioShow_BtnExit, ui_event_ScrVedioShow_BtnExit, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrVedioShow_BtnPrev, ui_event_ScrVedioShow_BtnPrev, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrVedioShow_BtnPlay, ui_event_ScrVedioShow_BtnPlay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrVedioShow_BtnNext, ui_event_ScrVedioShow_BtnNext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrVedioShow_Slider, ui_event_ScrVedioShow_Slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrVedioShow_ContMain, ui_event_ScrVedioShow_ContMain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrVedioShow, ui_event_ScrVedioShow, LV_EVENT_ALL, NULL);


}

void ui_ScrVedioShow_screen_destroy(void)
{
    if(ui_ScrVedioShow) lv_obj_del(ui_ScrVedioShow);

    // NULL screen variables
    ui_ScrVedioShow = NULL;
    ui_ScrVedioShow_ContMain = NULL;
    ui_ScrVedioShow_ContHeader = NULL;
    ui_ScrVedioShow_BtnExit = NULL;
    ui_ScrVedioShow_LabelExit = NULL;
    ui_ScrVedioShow_LabelTitle = NULL;
    ui_ScrVedioShow_ContFooter = NULL;
    ui_ScrVedioShow_ContPlayCtl = NULL;
    ui_ScrVedioShow_BtnPrev = NULL;
    ui_ScrVedioShow_LabelPrev = NULL;
    ui_ScrVedioShow_BtnPlay = NULL;
    ui_ScrVedioShow_LabelPlay = NULL;
    ui_ScrVedioShow_BtnNext = NULL;
    ui_ScrVedioShow_LabelNext = NULL;
    ui_ScrVedioShow_Slider = NULL;
    ui_ScrVedioShow_ContVolume = NULL;
    ui_ScrVedioShow_BarVolume = NULL;
    ui_ScrVedioShow_LabelVolSymbol = NULL;

}

void ui_ScrVedioShow_screen_relocalize(void)
{
    // label widgets on screen

}
