// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScrFileExplorer = NULL;
lv_obj_t * ui_ScrFileExplorer_ContMain1 = NULL;
lv_obj_t * ui_ScrFileExplorer_ContHeader = NULL;
lv_obj_t * ui_ScrFileExplorer_BtnExit = NULL;
lv_obj_t * ui_ScrFileExplorer_LabelExit = NULL;
lv_obj_t * ui_ScrFileExplorer_LabelTitle = NULL;
// event funtions
void ui_event_ScrFileExplorer_BtnExit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrMain,&ui_ScrFileExplorer,LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrMain_screen_init);
    }
}

/*文件浏览器的事件函数*/
void ui_event_ScrFileExplorer_FE(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED) {
        /*获取产生事件的组件*/
        lv_obj_t* file_explorer = (lv_obj_t*)lv_event_get_current_target(e);
        
        printf("clicked file:%s\n", lv_file_explorer_get_selected_file_name(file_explorer));
        
    }
}

// build funtions

void ui_ScrFileExplorer_screen_init(void)
{
    ui_ScrFileExplorer = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrFileExplorer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrFileExplorer_ContMain1 = lv_obj_create(ui_ScrFileExplorer);
    lv_obj_remove_style_all(ui_ScrFileExplorer_ContMain1);
    lv_obj_set_width(ui_ScrFileExplorer_ContMain1, lv_pct(100));
    lv_obj_set_height(ui_ScrFileExplorer_ContMain1, lv_pct(100));
    lv_obj_remove_flag(ui_ScrFileExplorer_ContMain1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrFileExplorer_ContMain1, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrFileExplorer_ContMain1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrFileExplorer_ContHeader = lv_obj_create(ui_ScrFileExplorer_ContMain1);
    lv_obj_remove_style_all(ui_ScrFileExplorer_ContHeader);
    lv_obj_set_width(ui_ScrFileExplorer_ContHeader, lv_pct(100));
    lv_obj_set_height(ui_ScrFileExplorer_ContHeader, lv_pct(10));
    lv_obj_remove_flag(ui_ScrFileExplorer_ContHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ScrFileExplorer_ContHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrFileExplorer_ContHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrFileExplorer_ContHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScrFileExplorer_ContHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrFileExplorer_BtnExit = lv_button_create(ui_ScrFileExplorer_ContHeader);
    lv_obj_set_width(ui_ScrFileExplorer_BtnExit, lv_pct(15));
    lv_obj_set_height(ui_ScrFileExplorer_BtnExit, lv_pct(100));
    lv_obj_set_x(ui_ScrFileExplorer_BtnExit, lv_pct(2));
    lv_obj_set_y(ui_ScrFileExplorer_BtnExit, lv_pct(0));
    lv_obj_add_flag(ui_ScrFileExplorer_BtnExit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrFileExplorer_BtnExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrFileExplorer_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrFileExplorer_BtnExit, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrFileExplorer_BtnExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrFileExplorer_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrFileExplorer_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrFileExplorer_LabelExit = lv_label_create(ui_ScrFileExplorer_BtnExit);
    lv_obj_set_width(ui_ScrFileExplorer_LabelExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrFileExplorer_LabelExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrFileExplorer_LabelExit, lv_pct(2));
    lv_obj_set_y(ui_ScrFileExplorer_LabelExit, lv_pct(0));
    lv_obj_set_align(ui_ScrFileExplorer_LabelExit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrFileExplorer_LabelExit, LV_SYMBOL_LEFT);
    lv_obj_set_style_text_color(ui_ScrFileExplorer_LabelExit, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrFileExplorer_LabelExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrFileExplorer_LabelExit, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrFileExplorer_LabelTitle = lv_label_create(ui_ScrFileExplorer_ContHeader);
    lv_obj_set_width(ui_ScrFileExplorer_LabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrFileExplorer_LabelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrFileExplorer_LabelTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrFileExplorer_LabelTitle, "File Explorer");
    lv_obj_set_style_text_font(ui_ScrFileExplorer_LabelTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);


    /*添加文件浏览器*/
    lv_obj_t* fe = lv_file_explorer_create(ui_ScrFileExplorer);
    lv_file_explorer_open_dir(fe, DRIVER_DIR);
    lv_obj_set_pos(fe, lv_pct(0), lv_pct(10));
    lv_obj_set_align(fe, LV_ALIGN_TOP_LEFT);
    lv_obj_set_size(fe, lv_pct(100), lv_pct(90));

    /*添加事件函数。点击了文件后就会触发*/
    lv_obj_add_event_cb(fe, ui_event_ScrFileExplorer_FE, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrFileExplorer_BtnExit, ui_event_ScrFileExplorer_BtnExit, LV_EVENT_ALL, NULL);
}

void ui_ScrFileExplorer_screen_destroy(void)
{
    if(ui_ScrFileExplorer) lv_obj_del(ui_ScrFileExplorer);

    // NULL screen variables
    ui_ScrFileExplorer = NULL;
    ui_ScrFileExplorer_ContMain1 = NULL;
    ui_ScrFileExplorer_ContHeader = NULL;
    ui_ScrFileExplorer_BtnExit = NULL;
    ui_ScrFileExplorer_LabelExit = NULL;
    ui_ScrFileExplorer_LabelTitle = NULL;

}

void ui_ScrFileExplorer_screen_relocalize(void)
{
    // label widgets on screen

}
