// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Mobile_Phone
#include"ui_ScrMain.h"

lv_obj_t * uic_ScrMain_LabelApp;
lv_obj_t * ui_ScrMain = NULL;
lv_obj_t * ui_ScrMain_ContBody = NULL;
lv_obj_t * ui_ScrMain_ContSetting = NULL;
lv_obj_t * ui_ScrMain_ImgBtnSetting = NULL;
lv_obj_t * ui_ScrMain_LabelSetting = NULL;
lv_obj_t * ui_ScrMain_ContCalendar = NULL;
lv_obj_t * ui_ScrMain_ImgBtnCalendar = NULL;
lv_obj_t * ui_ScrMain_LabelCalendar = NULL;
lv_obj_t * ui_ScrMain_ContWeather = NULL;
lv_obj_t * ui_ScrMain_ImgBtnWeather = NULL;
lv_obj_t * ui_ScrMain_LabelWeather = NULL;
lv_obj_t * ui_ScrMain_ContFe = NULL;
lv_obj_t * ui_ScrMain_ImgBtnFe = NULL;
lv_obj_t * ui_ScrMain_LabelFe = NULL;
lv_obj_t * ui_ScrMain_ContAlbum = NULL;
lv_obj_t * ui_ScrMain_ImgBtnAlbum = NULL;
lv_obj_t * ui_ScrMain_LabelAlbum = NULL;
lv_obj_t * ui_ScrMain_ContVedio = NULL;
lv_obj_t * ui_ScrMain_ImgBtnVedio = NULL;
lv_obj_t * ui_ScrMain_LabelVedio = NULL;
lv_obj_t * ui_ScrMain_ContMusic = NULL;
lv_obj_t * ui_ScrMain_ImgBtnMusic = NULL;
lv_obj_t * ui_ScrMain_LabelMusic = NULL;
lv_obj_t * ui_ScrMain_ContCamera = NULL;
lv_obj_t * ui_ScrMain_ImgBtnCamera = NULL;
lv_obj_t * ui_ScrMain_LabelCamera = NULL;
lv_obj_t * ui_ScrMain_ContAI = NULL;
lv_obj_t * ui_ScrMain_ImgBtnAI = NULL;
lv_obj_t * ui_ScrMain_LabelAI = NULL;
lv_obj_t * ui_ScrMain_ContRec = NULL;
lv_obj_t * ui_ScrMain_ImgBtnAI2 = NULL;
lv_obj_t * ui_ScrMain_LabelAI2 = NULL;
lv_obj_t * ui_ScrMain_ContHeader = NULL;
lv_obj_t * ui_ScrMain_LabelTime = NULL;
lv_obj_t * ui_ScrMain_ContTools = NULL;
lv_obj_t * ui_ScrMain_LabelBlueTooth = NULL;
lv_obj_t * ui_ScrMain_LabelWifi = NULL;
lv_obj_t * ui_ScrMain_LabelBatteryNum = NULL;
lv_obj_t * ui_ScrMain_LabelBattery = NULL;
// event funtions
void ui_event_ScrMain_ImgBtnSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scr_main_btn_setting_cb(e);
    }
}

void ui_event_ScrMain_ImgBtnCalendar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scr_main_btn_calendar_cb(e);
    }
}

void ui_event_ScrMain_ImgBtnWeather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrWeather,&ui_ScrMain,LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrWeather_screen_init);
    }
}

void ui_event_ScrMain_ImgBtnFe(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scr_main_btn_fe_cb(e);
    }
}

void ui_event_ScrMain_ImgBtnAlbum(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scr_main_btn_album_cb(e);
    }
}

void ui_event_ScrMain_ImgBtnVedio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scr_main_btn_vedio_cb(e);
    }
}

void ui_event_ScrMain_ImgBtnMusic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrMusic, &ui_ScrMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrMusic_screen_init);
    }
}

void ui_event_ScrMain_ImgBtnCamera(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scr_main_btn_camera_cb(e);
    }
}

void ui_event_ScrMain_ImgBtnAI(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scr_main_btn_ai_cb(e);
    }
}

void ui_event_ScrMain_ImgBtnAI2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrRec, &ui_ScrMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrRec_screen_init);
    }
}

// build funtions

void ui_ScrMain_screen_init(void)
{
    ui_ScrMain = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_ScrMain, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_ScrMain_screen_destroy);

    ui_ScrMain_ContBody = lv_obj_create(ui_ScrMain);
    lv_obj_remove_style_all(ui_ScrMain_ContBody);
    lv_obj_set_width(ui_ScrMain_ContBody, lv_pct(100));
    lv_obj_set_height(ui_ScrMain_ContBody, lv_pct(90));
    lv_obj_set_x(ui_ScrMain_ContBody, lv_pct(0));
    lv_obj_set_y(ui_ScrMain_ContBody, lv_pct(10));
    lv_obj_set_flex_flow(ui_ScrMain_ContBody, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ScrMain_ContBody, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ScrMain_ContBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMain_ContSetting = lv_obj_create(ui_ScrMain_ContBody);
    lv_obj_remove_style_all(ui_ScrMain_ContSetting);
    lv_obj_set_width(ui_ScrMain_ContSetting, lv_pct(25));
    lv_obj_set_height(ui_ScrMain_ContSetting, lv_pct(25));
    lv_obj_remove_flag(ui_ScrMain_ContSetting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMain_ImgBtnSetting = lv_imagebutton_create(ui_ScrMain_ContSetting);
    lv_imagebutton_set_src(ui_ScrMain_ImgBtnSetting, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_setting_png, NULL);
    lv_imagebutton_set_src(ui_ScrMain_ImgBtnSetting, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_setting_png, NULL);
    lv_obj_set_width(ui_ScrMain_ImgBtnSetting, lv_pct(70));
    lv_obj_set_height(ui_ScrMain_ImgBtnSetting, lv_pct(60));
    lv_obj_set_align(ui_ScrMain_ImgBtnSetting, LV_ALIGN_TOP_MID);
    lv_obj_add_state(ui_ScrMain_ImgBtnSetting, LV_STATE_USER_4);       /// States

    ui_ScrMain_LabelSetting = lv_label_create(ui_ScrMain_ContSetting);
    lv_obj_set_width(ui_ScrMain_LabelSetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMain_LabelSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMain_LabelSetting, lv_pct(0));
    lv_obj_set_y(ui_ScrMain_LabelSetting, lv_pct(62));
    lv_obj_set_align(ui_ScrMain_LabelSetting, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ScrMain_LabelSetting, "setting");
    lv_obj_set_style_text_align(ui_ScrMain_LabelSetting, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMain_LabelSetting, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMain_ContCalendar = lv_obj_create(ui_ScrMain_ContBody);
    lv_obj_remove_style_all(ui_ScrMain_ContCalendar);
    lv_obj_set_width(ui_ScrMain_ContCalendar, lv_pct(25));
    lv_obj_set_height(ui_ScrMain_ContCalendar, lv_pct(25));
    lv_obj_set_x(ui_ScrMain_ContCalendar, lv_pct(25));
    lv_obj_set_y(ui_ScrMain_ContCalendar, lv_pct(0));
    lv_obj_remove_flag(ui_ScrMain_ContCalendar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMain_ImgBtnCalendar = lv_imagebutton_create(ui_ScrMain_ContCalendar);
    lv_imagebutton_set_src(ui_ScrMain_ImgBtnCalendar, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_calendar_png, NULL);
    lv_obj_set_width(ui_ScrMain_ImgBtnCalendar, lv_pct(70));
    lv_obj_set_height(ui_ScrMain_ImgBtnCalendar, lv_pct(60));
    lv_obj_set_align(ui_ScrMain_ImgBtnCalendar, LV_ALIGN_TOP_MID);

    ui_ScrMain_LabelCalendar = lv_label_create(ui_ScrMain_ContCalendar);
    lv_obj_set_width(ui_ScrMain_LabelCalendar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMain_LabelCalendar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMain_LabelCalendar, lv_pct(0));
    lv_obj_set_y(ui_ScrMain_LabelCalendar, lv_pct(62));
    lv_obj_set_align(ui_ScrMain_LabelCalendar, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ScrMain_LabelCalendar, "calendar");
    lv_obj_set_style_text_align(ui_ScrMain_LabelCalendar, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMain_LabelCalendar, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMain_ContWeather = lv_obj_create(ui_ScrMain_ContBody);
    lv_obj_remove_style_all(ui_ScrMain_ContWeather);
    lv_obj_set_width(ui_ScrMain_ContWeather, lv_pct(25));
    lv_obj_set_height(ui_ScrMain_ContWeather, lv_pct(25));
    lv_obj_set_x(ui_ScrMain_ContWeather, lv_pct(50));
    lv_obj_set_y(ui_ScrMain_ContWeather, lv_pct(0));
    lv_obj_remove_flag(ui_ScrMain_ContWeather, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMain_ImgBtnWeather = lv_imagebutton_create(ui_ScrMain_ContWeather);
    lv_imagebutton_set_src(ui_ScrMain_ImgBtnWeather, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_weather_png, NULL);
    lv_obj_set_width(ui_ScrMain_ImgBtnWeather, lv_pct(70));
    lv_obj_set_height(ui_ScrMain_ImgBtnWeather, lv_pct(60));
    lv_obj_set_align(ui_ScrMain_ImgBtnWeather, LV_ALIGN_TOP_MID);

    ui_ScrMain_LabelWeather = lv_label_create(ui_ScrMain_ContWeather);
    lv_obj_set_width(ui_ScrMain_LabelWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMain_LabelWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMain_LabelWeather, lv_pct(0));
    lv_obj_set_y(ui_ScrMain_LabelWeather, lv_pct(62));
    lv_obj_set_align(ui_ScrMain_LabelWeather, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ScrMain_LabelWeather, "weather");
    lv_obj_set_style_text_align(ui_ScrMain_LabelWeather, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMain_LabelWeather, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMain_ContFe = lv_obj_create(ui_ScrMain_ContBody);
    lv_obj_remove_style_all(ui_ScrMain_ContFe);
    lv_obj_set_width(ui_ScrMain_ContFe, lv_pct(25));
    lv_obj_set_height(ui_ScrMain_ContFe, lv_pct(25));
    lv_obj_set_x(ui_ScrMain_ContFe, lv_pct(75));
    lv_obj_set_y(ui_ScrMain_ContFe, lv_pct(0));
    lv_obj_remove_flag(ui_ScrMain_ContFe, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMain_ImgBtnFe = lv_imagebutton_create(ui_ScrMain_ContFe);
    lv_imagebutton_set_src(ui_ScrMain_ImgBtnFe, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_fe_png, NULL);
    lv_obj_set_width(ui_ScrMain_ImgBtnFe, lv_pct(70));
    lv_obj_set_height(ui_ScrMain_ImgBtnFe, lv_pct(60));
    lv_obj_set_align(ui_ScrMain_ImgBtnFe, LV_ALIGN_TOP_MID);

    ui_ScrMain_LabelFe = lv_label_create(ui_ScrMain_ContFe);
    lv_obj_set_width(ui_ScrMain_LabelFe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMain_LabelFe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMain_LabelFe, lv_pct(0));
    lv_obj_set_y(ui_ScrMain_LabelFe, lv_pct(62));
    lv_obj_set_align(ui_ScrMain_LabelFe, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ScrMain_LabelFe, "file\nexplorer");
    lv_obj_set_style_text_align(ui_ScrMain_LabelFe, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMain_LabelFe, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMain_ContAlbum = lv_obj_create(ui_ScrMain_ContBody);
    lv_obj_remove_style_all(ui_ScrMain_ContAlbum);
    lv_obj_set_width(ui_ScrMain_ContAlbum, lv_pct(25));
    lv_obj_set_height(ui_ScrMain_ContAlbum, lv_pct(25));
    lv_obj_set_x(ui_ScrMain_ContAlbum, lv_pct(0));
    lv_obj_set_y(ui_ScrMain_ContAlbum, lv_pct(25));
    lv_obj_remove_flag(ui_ScrMain_ContAlbum, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMain_ImgBtnAlbum = lv_imagebutton_create(ui_ScrMain_ContAlbum);
    lv_imagebutton_set_src(ui_ScrMain_ImgBtnAlbum, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_album_png, NULL);
    lv_obj_set_width(ui_ScrMain_ImgBtnAlbum, lv_pct(70));
    lv_obj_set_height(ui_ScrMain_ImgBtnAlbum, lv_pct(60));
    lv_obj_set_align(ui_ScrMain_ImgBtnAlbum, LV_ALIGN_TOP_MID);

    ui_ScrMain_LabelAlbum = lv_label_create(ui_ScrMain_ContAlbum);
    lv_obj_set_width(ui_ScrMain_LabelAlbum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMain_LabelAlbum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMain_LabelAlbum, lv_pct(0));
    lv_obj_set_y(ui_ScrMain_LabelAlbum, lv_pct(62));
    lv_obj_set_align(ui_ScrMain_LabelAlbum, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ScrMain_LabelAlbum, "album");
    lv_obj_set_style_text_align(ui_ScrMain_LabelAlbum, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMain_LabelAlbum, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMain_ContVedio = lv_obj_create(ui_ScrMain_ContBody);
    lv_obj_remove_style_all(ui_ScrMain_ContVedio);
    lv_obj_set_width(ui_ScrMain_ContVedio, lv_pct(25));
    lv_obj_set_height(ui_ScrMain_ContVedio, lv_pct(25));
    lv_obj_set_x(ui_ScrMain_ContVedio, lv_pct(25));
    lv_obj_set_y(ui_ScrMain_ContVedio, lv_pct(25));
    lv_obj_remove_flag(ui_ScrMain_ContVedio, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMain_ImgBtnVedio = lv_imagebutton_create(ui_ScrMain_ContVedio);
    lv_imagebutton_set_src(ui_ScrMain_ImgBtnVedio, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_vedio_png, NULL);
    lv_obj_set_width(ui_ScrMain_ImgBtnVedio, lv_pct(70));
    lv_obj_set_height(ui_ScrMain_ImgBtnVedio, lv_pct(60));
    lv_obj_set_align(ui_ScrMain_ImgBtnVedio, LV_ALIGN_TOP_MID);

    ui_ScrMain_LabelVedio = lv_label_create(ui_ScrMain_ContVedio);
    lv_obj_set_width(ui_ScrMain_LabelVedio, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMain_LabelVedio, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMain_LabelVedio, lv_pct(0));
    lv_obj_set_y(ui_ScrMain_LabelVedio, lv_pct(62));
    lv_obj_set_align(ui_ScrMain_LabelVedio, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ScrMain_LabelVedio, "vedio");
    lv_obj_set_style_text_align(ui_ScrMain_LabelVedio, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMain_LabelVedio, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMain_ContMusic = lv_obj_create(ui_ScrMain_ContBody);
    lv_obj_remove_style_all(ui_ScrMain_ContMusic);
    lv_obj_set_width(ui_ScrMain_ContMusic, lv_pct(25));
    lv_obj_set_height(ui_ScrMain_ContMusic, lv_pct(25));
    lv_obj_set_x(ui_ScrMain_ContMusic, lv_pct(50));
    lv_obj_set_y(ui_ScrMain_ContMusic, lv_pct(25));
    lv_obj_remove_flag(ui_ScrMain_ContMusic, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMain_ImgBtnMusic = lv_imagebutton_create(ui_ScrMain_ContMusic);
    lv_imagebutton_set_src(ui_ScrMain_ImgBtnMusic, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_music_png, NULL);
    lv_obj_set_width(ui_ScrMain_ImgBtnMusic, lv_pct(70));
    lv_obj_set_height(ui_ScrMain_ImgBtnMusic, lv_pct(60));
    lv_obj_set_align(ui_ScrMain_ImgBtnMusic, LV_ALIGN_TOP_MID);

    ui_ScrMain_LabelMusic = lv_label_create(ui_ScrMain_ContMusic);
    lv_obj_set_width(ui_ScrMain_LabelMusic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMain_LabelMusic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMain_LabelMusic, lv_pct(0));
    lv_obj_set_y(ui_ScrMain_LabelMusic, lv_pct(62));
    lv_obj_set_align(ui_ScrMain_LabelMusic, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ScrMain_LabelMusic, "music\n");
    lv_obj_set_style_text_align(ui_ScrMain_LabelMusic, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMain_LabelMusic, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMain_ContCamera = lv_obj_create(ui_ScrMain_ContBody);
    lv_obj_remove_style_all(ui_ScrMain_ContCamera);
    lv_obj_set_width(ui_ScrMain_ContCamera, lv_pct(25));
    lv_obj_set_height(ui_ScrMain_ContCamera, lv_pct(25));
    lv_obj_set_x(ui_ScrMain_ContCamera, lv_pct(75));
    lv_obj_set_y(ui_ScrMain_ContCamera, lv_pct(25));
    lv_obj_remove_flag(ui_ScrMain_ContCamera, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMain_ImgBtnCamera = lv_imagebutton_create(ui_ScrMain_ContCamera);
    lv_imagebutton_set_src(ui_ScrMain_ImgBtnCamera, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_camera_png, NULL);
    lv_obj_set_width(ui_ScrMain_ImgBtnCamera, lv_pct(70));
    lv_obj_set_height(ui_ScrMain_ImgBtnCamera, lv_pct(60));
    lv_obj_set_align(ui_ScrMain_ImgBtnCamera, LV_ALIGN_TOP_MID);

    ui_ScrMain_LabelCamera = lv_label_create(ui_ScrMain_ContCamera);
    lv_obj_set_width(ui_ScrMain_LabelCamera, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMain_LabelCamera, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMain_LabelCamera, lv_pct(0));
    lv_obj_set_y(ui_ScrMain_LabelCamera, lv_pct(62));
    lv_obj_set_align(ui_ScrMain_LabelCamera, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ScrMain_LabelCamera, "camera");
    lv_obj_set_style_text_align(ui_ScrMain_LabelCamera, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMain_LabelCamera, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMain_ContAI = lv_obj_create(ui_ScrMain_ContBody);
    lv_obj_remove_style_all(ui_ScrMain_ContAI);
    lv_obj_set_width(ui_ScrMain_ContAI, lv_pct(25));
    lv_obj_set_height(ui_ScrMain_ContAI, lv_pct(25));
    lv_obj_set_x(ui_ScrMain_ContAI, lv_pct(75));
    lv_obj_set_y(ui_ScrMain_ContAI, lv_pct(25));
    lv_obj_remove_flag(ui_ScrMain_ContAI, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMain_ImgBtnAI = lv_imagebutton_create(ui_ScrMain_ContAI);
    lv_imagebutton_set_src(ui_ScrMain_ImgBtnAI, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_ai_png, NULL);
    lv_obj_set_width(ui_ScrMain_ImgBtnAI, lv_pct(70));
    lv_obj_set_height(ui_ScrMain_ImgBtnAI, lv_pct(60));
    lv_obj_set_align(ui_ScrMain_ImgBtnAI, LV_ALIGN_TOP_MID);

    ui_ScrMain_LabelAI = lv_label_create(ui_ScrMain_ContAI);
    lv_obj_set_width(ui_ScrMain_LabelAI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMain_LabelAI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMain_LabelAI, lv_pct(0));
    lv_obj_set_y(ui_ScrMain_LabelAI, lv_pct(62));
    lv_obj_set_align(ui_ScrMain_LabelAI, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ScrMain_LabelAI, "AI");
    lv_obj_set_style_text_align(ui_ScrMain_LabelAI, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMain_LabelAI, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMain_ContRec = lv_obj_create(ui_ScrMain_ContBody);
    lv_obj_remove_style_all(ui_ScrMain_ContRec);
    lv_obj_set_width(ui_ScrMain_ContRec, lv_pct(25));
    lv_obj_set_height(ui_ScrMain_ContRec, lv_pct(25));
    lv_obj_set_x(ui_ScrMain_ContRec, lv_pct(75));
    lv_obj_set_y(ui_ScrMain_ContRec, lv_pct(25));
    lv_obj_remove_flag(ui_ScrMain_ContRec, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMain_ImgBtnAI2 = lv_imagebutton_create(ui_ScrMain_ContRec);
    lv_imagebutton_set_src(ui_ScrMain_ImgBtnAI2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_ai_png, NULL);
    lv_obj_set_width(ui_ScrMain_ImgBtnAI2, lv_pct(70));
    lv_obj_set_height(ui_ScrMain_ImgBtnAI2, lv_pct(60));
    lv_obj_set_align(ui_ScrMain_ImgBtnAI2, LV_ALIGN_TOP_MID);

    ui_ScrMain_LabelAI2 = lv_label_create(ui_ScrMain_ContRec);
    lv_obj_set_width(ui_ScrMain_LabelAI2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMain_LabelAI2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMain_LabelAI2, lv_pct(0));
    lv_obj_set_y(ui_ScrMain_LabelAI2, lv_pct(62));
    lv_obj_set_align(ui_ScrMain_LabelAI2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ScrMain_LabelAI2, "rec\n");
    lv_obj_set_style_text_align(ui_ScrMain_LabelAI2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMain_LabelAI2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMain_ContHeader = lv_obj_create(ui_ScrMain);
    lv_obj_remove_style_all(ui_ScrMain_ContHeader);
    lv_obj_set_width(ui_ScrMain_ContHeader, lv_pct(100));
    lv_obj_set_height(ui_ScrMain_ContHeader, lv_pct(10));
    lv_obj_remove_flag(ui_ScrMain_ContHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMain_LabelTime = lv_label_create(ui_ScrMain_ContHeader);
    lv_obj_set_width(ui_ScrMain_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMain_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMain_LabelTime, lv_pct(3));
    lv_obj_set_y(ui_ScrMain_LabelTime, lv_pct(0));
    lv_obj_set_align(ui_ScrMain_LabelTime, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ScrMain_LabelTime, "11:52");

    ui_ScrMain_ContTools = lv_obj_create(ui_ScrMain_ContHeader);
    lv_obj_remove_style_all(ui_ScrMain_ContTools);
    lv_obj_set_width(ui_ScrMain_ContTools, lv_pct(60));
    lv_obj_set_height(ui_ScrMain_ContTools, lv_pct(100));
    lv_obj_set_x(ui_ScrMain_ContTools, lv_pct(-4));
    lv_obj_set_y(ui_ScrMain_ContTools, lv_pct(0));
    lv_obj_set_align(ui_ScrMain_ContTools, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_ScrMain_ContTools, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ScrMain_ContTools, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ScrMain_ContTools, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMain_LabelBlueTooth = lv_label_create(ui_ScrMain_ContTools);
    lv_obj_set_width(ui_ScrMain_LabelBlueTooth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMain_LabelBlueTooth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMain_LabelBlueTooth, lv_pct(5));
    lv_obj_set_y(ui_ScrMain_LabelBlueTooth, lv_pct(0));
    lv_obj_set_align(ui_ScrMain_LabelBlueTooth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrMain_LabelBlueTooth, "ble");

    ui_ScrMain_LabelWifi = lv_label_create(ui_ScrMain_ContTools);
    lv_obj_set_width(ui_ScrMain_LabelWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMain_LabelWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMain_LabelWifi, lv_pct(5));
    lv_obj_set_y(ui_ScrMain_LabelWifi, lv_pct(0));
    lv_obj_set_align(ui_ScrMain_LabelWifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrMain_LabelWifi, "wifi");

    ui_ScrMain_LabelBatteryNum = lv_label_create(ui_ScrMain_ContTools);
    lv_obj_set_width(ui_ScrMain_LabelBatteryNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMain_LabelBatteryNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrMain_LabelBatteryNum, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ScrMain_LabelBatteryNum, "99%");

    ui_ScrMain_LabelBattery = lv_label_create(ui_ScrMain_ContTools);
    lv_obj_set_width(ui_ScrMain_LabelBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMain_LabelBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMain_LabelBattery, lv_pct(-5));
    lv_obj_set_y(ui_ScrMain_LabelBattery, lv_pct(0));
    lv_obj_set_align(ui_ScrMain_LabelBattery, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_ScrMain_LabelBattery, "batte");

    lv_obj_add_event_cb(ui_ScrMain_ImgBtnSetting, ui_event_ScrMain_ImgBtnSetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMain_ImgBtnCalendar, ui_event_ScrMain_ImgBtnCalendar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMain_ImgBtnWeather, ui_event_ScrMain_ImgBtnWeather, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMain_ImgBtnFe, ui_event_ScrMain_ImgBtnFe, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMain_ImgBtnAlbum, ui_event_ScrMain_ImgBtnAlbum, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMain_ImgBtnVedio, ui_event_ScrMain_ImgBtnVedio, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMain_ImgBtnMusic, ui_event_ScrMain_ImgBtnMusic, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMain_ImgBtnCamera, ui_event_ScrMain_ImgBtnCamera, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMain_ImgBtnAI, ui_event_ScrMain_ImgBtnAI, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMain_ImgBtnAI2, ui_event_ScrMain_ImgBtnAI2, LV_EVENT_ALL, NULL);
    uic_ScrMain_LabelApp = ui_ScrMain_LabelSetting;

}

void ui_ScrMain_screen_destroy(void)
{
    if(ui_ScrMain) lv_obj_del(ui_ScrMain);

    // NULL screen variables
    ui_ScrMain = NULL;
    ui_ScrMain_ContBody = NULL;
    ui_ScrMain_ContSetting = NULL;
    ui_ScrMain_ImgBtnSetting = NULL;
    uic_ScrMain_LabelApp = NULL;
    ui_ScrMain_LabelSetting = NULL;
    ui_ScrMain_ContCalendar = NULL;
    ui_ScrMain_ImgBtnCalendar = NULL;
    ui_ScrMain_LabelCalendar = NULL;
    ui_ScrMain_ContWeather = NULL;
    ui_ScrMain_ImgBtnWeather = NULL;
    ui_ScrMain_LabelWeather = NULL;
    ui_ScrMain_ContFe = NULL;
    ui_ScrMain_ImgBtnFe = NULL;
    ui_ScrMain_LabelFe = NULL;
    ui_ScrMain_ContAlbum = NULL;
    ui_ScrMain_ImgBtnAlbum = NULL;
    ui_ScrMain_LabelAlbum = NULL;
    ui_ScrMain_ContVedio = NULL;
    ui_ScrMain_ImgBtnVedio = NULL;
    ui_ScrMain_LabelVedio = NULL;
    ui_ScrMain_ContMusic = NULL;
    ui_ScrMain_ImgBtnMusic = NULL;
    ui_ScrMain_LabelMusic = NULL;
    ui_ScrMain_ContCamera = NULL;
    ui_ScrMain_ImgBtnCamera = NULL;
    ui_ScrMain_LabelCamera = NULL;
    ui_ScrMain_ContAI = NULL;
    ui_ScrMain_ImgBtnAI = NULL;
    ui_ScrMain_LabelAI = NULL;
    ui_ScrMain_ContRec = NULL;
    ui_ScrMain_ImgBtnAI2 = NULL;
    ui_ScrMain_LabelAI2 = NULL;
    ui_ScrMain_ContHeader = NULL;
    ui_ScrMain_LabelTime = NULL;
    ui_ScrMain_ContTools = NULL;
    ui_ScrMain_LabelBlueTooth = NULL;
    ui_ScrMain_LabelWifi = NULL;
    ui_ScrMain_LabelBatteryNum = NULL;
    ui_ScrMain_LabelBattery = NULL;

}

void ui_ScrMain_screen_relocalize(void)
{
    // label widgets on screen

}
