// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"
#include"Core/vedio.h"
lv_obj_t * ui_ScrVedio = NULL;
lv_obj_t * ui_ScrVedio_ContMain = NULL;
lv_obj_t * ui_ScrVedio_ContHeader = NULL;
lv_obj_t * ui_ScrVedio_BtnExit = NULL;
lv_obj_t * ui_ScrVedio_Label1 = NULL;
lv_obj_t * ui_ScrVedio_LabelTitle = NULL;
lv_obj_t * ui_ScrVedio_PanelBody = NULL;
lv_obj_t * ui_ScrVedio_ContVedio = NULL;
lv_obj_t * ui_ScrVedio_BtnVedio = NULL;
lv_obj_t * ui_ScrVedio_LabelVedioSymbol = NULL;
lv_obj_t * ui_ScrVedio_LabelVedioName = NULL;
lv_obj_t* ui_ScrVedio_Table = NULL; /*自定义*/
// event funtions
void ui_event_ScrVedio_BtnExit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) 
    {
        _ui_screen_change(&ui_ScrMain,&ui_ScrMain,LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrMain_screen_init);
    }
}

//void ui_event_ScrVedio_BtnVedio(lv_event_t * e)
//{
//    lv_event_code_t event_code = lv_event_get_code(e);
//
//    if(event_code == LV_EVENT_CLICKED) {
//        _ui_screen_change(&ui_ScrVedioShow,&ui_ScrVedio,LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrVedioShow_screen_init);
//    }
//}

void ui_event_ScrVedio_Table(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t* table = (lv_obj_t*)lv_event_get_target(e);
    uint32_t rowCnt= lv_table_get_row_count(table);
    if (rowCnt == 0) return; /*只有0行，也就是说现在没有单元值*/
    /*printf("cnt:%d\n", cnt); */

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        uint32_t row = 0;
        uint32_t col = 0;
        lv_table_get_selected_cell(table, &row, &col);
        //const char* text = lv_table_get_cell_value(table, row, col);

       
        //printf("choose vedio index:%d\n", row);
        //printf("table item text:%s\n", text + 3);

        _ui_screen_change(&ui_ScrVedioShow, &ui_ScrVedio, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrVedioShow_screen_init);

        vedioHandle.isDispVedio = 1; /*代表要开始显示图片了*/
    }
}



// build funtions

void ui_ScrVedio_screen_init(void)
{
    ui_ScrVedio = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrVedio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_ScrVedio, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_ScrVedio_screen_destroy);

    ui_ScrVedio_ContMain = lv_obj_create(ui_ScrVedio);
    lv_obj_remove_style_all(ui_ScrVedio_ContMain);
    lv_obj_set_width(ui_ScrVedio_ContMain, lv_pct(100));
    lv_obj_set_height(ui_ScrVedio_ContMain, lv_pct(100));
    lv_obj_remove_flag(ui_ScrVedio_ContMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrVedio_ContMain, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrVedio_ContMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedio_ContHeader = lv_obj_create(ui_ScrVedio_ContMain);
    lv_obj_remove_style_all(ui_ScrVedio_ContHeader);
    lv_obj_set_width(ui_ScrVedio_ContHeader, lv_pct(100));
    lv_obj_set_height(ui_ScrVedio_ContHeader, lv_pct(10));
    lv_obj_remove_flag(ui_ScrVedio_ContHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ScrVedio_ContHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrVedio_ContHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrVedio_ContHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScrVedio_ContHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedio_BtnExit = lv_button_create(ui_ScrVedio_ContHeader);
    lv_obj_set_width(ui_ScrVedio_BtnExit, lv_pct(15));
    lv_obj_set_height(ui_ScrVedio_BtnExit, lv_pct(100));
    lv_obj_set_x(ui_ScrVedio_BtnExit, lv_pct(2));
    lv_obj_set_y(ui_ScrVedio_BtnExit, lv_pct(0));
    lv_obj_add_flag(ui_ScrVedio_BtnExit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrVedio_BtnExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrVedio_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrVedio_BtnExit, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrVedio_BtnExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrVedio_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrVedio_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedio_Label1 = lv_label_create(ui_ScrVedio_BtnExit);
    lv_obj_set_width(ui_ScrVedio_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrVedio_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrVedio_Label1, lv_pct(2));
    lv_obj_set_y(ui_ScrVedio_Label1, lv_pct(0));
    lv_obj_set_align(ui_ScrVedio_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrVedio_Label1, LV_SYMBOL_LEFT);
    lv_obj_set_style_text_color(ui_ScrVedio_Label1, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrVedio_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrVedio_Label1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrVedio_LabelTitle = lv_label_create(ui_ScrVedio_ContHeader);
    lv_obj_set_width(ui_ScrVedio_LabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrVedio_LabelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrVedio_LabelTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrVedio_LabelTitle, "Vedio");
    lv_obj_set_style_text_font(ui_ScrVedio_LabelTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);


    /*表格显示视频的名*/
    ui_ScrVedio_Table = lv_table_create(ui_ScrVedio);
    lv_obj_set_style_text_font(ui_ScrVedio_Table, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_size(ui_ScrVedio_Table, lv_pct(100), lv_pct(90));
    lv_obj_set_align(ui_ScrVedio_Table, LV_ALIGN_TOP_LEFT);
    lv_obj_set_pos(ui_ScrVedio_Table, lv_pct(0), lv_pct(10));

    lv_table_set_column_width(ui_ScrVedio_Table, 0, lv_pct(100));
    lv_table_set_column_count(ui_ScrVedio_Table, 1);
    lv_table_set_row_count(ui_ScrVedio_Table, 0);

    lv_obj_add_event_cb(ui_ScrVedio_Table, ui_event_ScrVedio_Table, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrVedio_BtnExit, ui_event_ScrVedio_BtnExit, LV_EVENT_ALL, NULL);


    vedioHandle.isInit = 1;
}

void ui_ScrVedio_screen_destroy(void)
{
    if(ui_ScrVedio) lv_obj_del(ui_ScrVedio);

    // NULL screen variables
    ui_ScrVedio = NULL;
    ui_ScrVedio_ContMain = NULL;
    ui_ScrVedio_ContHeader = NULL;
    ui_ScrVedio_BtnExit = NULL;
    ui_ScrVedio_Label1 = NULL;
    ui_ScrVedio_LabelTitle = NULL;
    ui_ScrVedio_PanelBody = NULL;
    ui_ScrVedio_ContVedio = NULL;
    ui_ScrVedio_BtnVedio = NULL;
    ui_ScrVedio_LabelVedioSymbol = NULL;
    ui_ScrVedio_LabelVedioName = NULL;

}

void ui_ScrVedio_screen_relocalize(void)
{
    // label widgets on screen

}
