// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCRFILEEXPLORER_H
#define UI_SCRFILEEXPLORER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrFileExplorer
extern void ui_ScrFileExplorer_screen_init(void);
extern void ui_ScrFileExplorer_screen_destroy(void);
extern void ui_ScrFileExplorer_screen_relocalize(void);
extern lv_obj_t * ui_ScrFileExplorer;
extern lv_obj_t * ui_ScrFileExplorer_ContMain1;
extern lv_obj_t * ui_ScrFileExplorer_ContHeader;
extern void ui_event_ScrFileExplorer_BtnExit(lv_event_t * e);
extern lv_obj_t * ui_ScrFileExplorer_BtnExit;
extern lv_obj_t * ui_ScrFileExplorer_LabelExit;
extern lv_obj_t * ui_ScrFileExplorer_LabelTitle;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

