// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Mobile_Phone

#include "../ui.h"


lv_obj_t * ui_ScrWeather = NULL;
lv_obj_t * ui_ContMain = NULL;
lv_obj_t * ui_ScrWeather_ContHeader = NULL;
lv_obj_t * ui_ScrWeather_BtnExit = NULL;
lv_obj_t * ui_ScrWeather_LabelExit = NULL;
lv_obj_t * ui_ScrWeather_LabelTitle = NULL;
lv_obj_t * ui_ScrWeather_BtnReflush = NULL;
lv_obj_t * ui_ScrWeather_LabelReflush = NULL;
lv_obj_t * ui_ContTools = NULL;
lv_obj_t * ui_ScrWeather_DdSelectCity = NULL;
lv_obj_t * ui_ContBody = NULL;
lv_obj_t * ui_PanelBody = NULL;
lv_obj_t * ui_ContCurWeather = NULL;
lv_obj_t * ui_LabelCurTemp = NULL;
lv_obj_t * ui_LabelTodayWeather = NULL;
lv_obj_t * ui_ContDaysWeather = NULL;
lv_obj_t * ui_ContWeatherInfo1 = NULL;
lv_obj_t * ui_LabelDate1 = NULL;
lv_obj_t * ui_ImgWeather1 = NULL;
lv_obj_t * ui_LabelPrecip1 = NULL;
lv_obj_t * ui_LabelTodayTemp1 = NULL;
lv_obj_t * ui_ContWeatherInfo3 = NULL;
lv_obj_t * ui_LabelDate3 = NULL;
lv_obj_t * ui_ImgWeather3 = NULL;
lv_obj_t * ui_LabelPrecip3 = NULL;
lv_obj_t * ui_LabelTodayTemp3 = NULL;
lv_obj_t * ui_ContWeatherInfo4 = NULL;
lv_obj_t * ui_LabelDate4 = NULL;
lv_obj_t * ui_ImgWeather4 = NULL;
lv_obj_t * ui_LabelPrecip4 = NULL;
lv_obj_t * ui_LabelTodayTemp4 = NULL;
lv_obj_t * ui_ContDetailInfo = NULL;
lv_obj_t * ui_ContRainFall = NULL;
lv_obj_t * ui_ImgRainfall = NULL;
lv_obj_t * ui_LabelRainfall = NULL;
lv_obj_t * ui_ContHumidity = NULL;
lv_obj_t * ui_ImgHumidity = NULL;
lv_obj_t * ui_LabelHumidity = NULL;
lv_obj_t * ui_ContWind = NULL;
lv_obj_t * ui_ImgWind = NULL;
lv_obj_t * ui_LabelWind = NULL;
lv_obj_t * ui_ContWindSpeed = NULL;
lv_obj_t * ui_ImgWindSpeed = NULL;
lv_obj_t * ui_LabelWindSpeed = NULL;
lv_obj_t* ui_ScrWeather_Mask = NULL;
lv_obj_t* ui_ScrWeather_Spinner = NULL;
lv_obj_t* ui_ScrWeather_LabelResponseRes = NULL;

// event funtions
void ui_event_ScrWeather_BtnExit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScrMain,&ui_ScrWeather,LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrMain_screen_init);
    }
}

void ui_event_ScrWeather_BtnReflush(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        scr_weather_btn_reflush_cb(e);
    }
}

void ui_event_ScrWeather_DdSelectCity(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        scr_weather_dd_select_city_cb(e);
    }
}

// build funtions

void ui_ScrWeather_screen_init(void)
{
    ui_ScrWeather = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContMain = lv_obj_create(ui_ScrWeather);
    lv_obj_remove_style_all(ui_ContMain);
    lv_obj_set_width(ui_ContMain, lv_pct(100));
    lv_obj_set_height(ui_ContMain, lv_pct(100));
    lv_obj_set_align(ui_ContMain, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContMain, lv_color_hex(0xF7F7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrWeather_ContHeader = lv_obj_create(ui_ContMain);
    lv_obj_remove_style_all(ui_ScrWeather_ContHeader);
    lv_obj_set_width(ui_ScrWeather_ContHeader, lv_pct(100));
    lv_obj_set_height(ui_ScrWeather_ContHeader, lv_pct(10));
    lv_obj_remove_flag(ui_ScrWeather_ContHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrWeather_ContHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrWeather_ContHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScrWeather_ContHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrWeather_ContHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrWeather_ContHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScrWeather_ContHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ScrWeather_ContHeader, lv_color_hex(0xEEEAEE), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrWeather_ContHeader, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ScrWeather_BtnExit = lv_button_create(ui_ScrWeather_ContHeader);
    lv_obj_set_height(ui_ScrWeather_BtnExit, lv_pct(100));
    lv_obj_set_width(ui_ScrWeather_BtnExit, LV_SIZE_CONTENT);   /// 15
    lv_obj_add_flag(ui_ScrWeather_BtnExit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrWeather_BtnExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrWeather_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrWeather_BtnExit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrWeather_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrWeather_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrWeather_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrWeather_LabelExit = lv_label_create(ui_ScrWeather_BtnExit);
    lv_obj_set_width(ui_ScrWeather_LabelExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrWeather_LabelExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrWeather_LabelExit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrWeather_LabelExit, LV_SYMBOL_LEFT);
    lv_obj_set_style_text_color(ui_ScrWeather_LabelExit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrWeather_LabelExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrWeather_LabelExit, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrWeather_LabelTitle = lv_label_create(ui_ScrWeather_ContHeader);
    lv_obj_set_width(ui_ScrWeather_LabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrWeather_LabelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrWeather_LabelTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrWeather_LabelTitle, "HangZhou");
    lv_obj_set_style_text_font(ui_ScrWeather_LabelTitle, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrWeather_BtnReflush = lv_button_create(ui_ScrWeather_ContHeader);
    lv_obj_set_height(ui_ScrWeather_BtnReflush, lv_pct(100));
    lv_obj_set_width(ui_ScrWeather_BtnReflush, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_align(ui_ScrWeather_BtnReflush, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ScrWeather_BtnReflush, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrWeather_BtnReflush, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrWeather_BtnReflush, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrWeather_BtnReflush, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrWeather_BtnReflush, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrWeather_BtnReflush, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrWeather_BtnReflush, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrWeather_LabelReflush = lv_label_create(ui_ScrWeather_BtnReflush);
    lv_obj_set_width(ui_ScrWeather_LabelReflush, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrWeather_LabelReflush, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrWeather_LabelReflush, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrWeather_LabelReflush, LV_SYMBOL_REFRESH);
    lv_obj_set_style_text_color(ui_ScrWeather_LabelReflush, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrWeather_LabelReflush, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrWeather_LabelReflush, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContTools = lv_obj_create(ui_ContMain);
    lv_obj_remove_style_all(ui_ContTools);
    lv_obj_set_width(ui_ContTools, lv_pct(100));
    lv_obj_set_height(ui_ContTools, lv_pct(10));
    lv_obj_set_x(ui_ContTools, lv_pct(0));
    lv_obj_set_y(ui_ContTools, lv_pct(10));
    lv_obj_remove_flag(ui_ContTools, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContTools, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContTools, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContTools, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrWeather_DdSelectCity = lv_dropdown_create(ui_ContTools);
    lv_dropdown_set_options(ui_ScrWeather_DdSelectCity, "HangZhou\nShangHai\nFuZhou\nBeiJing\nShenZhen");
    lv_obj_set_width(ui_ScrWeather_DdSelectCity, lv_pct(50));
    lv_obj_set_height(ui_ScrWeather_DdSelectCity, lv_pct(100));
    lv_obj_set_align(ui_ScrWeather_DdSelectCity, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ScrWeather_DdSelectCity, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_ScrWeather_DdSelectCity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrWeather_DdSelectCity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrWeather_DdSelectCity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContBody = lv_obj_create(ui_ContMain);
    lv_obj_remove_style_all(ui_ContBody);
    lv_obj_set_width(ui_ContBody, lv_pct(100));
    lv_obj_set_height(ui_ContBody, lv_pct(80));
    lv_obj_set_x(ui_ContBody, lv_pct(0));
    lv_obj_set_y(ui_ContBody, lv_pct(20));
    lv_obj_add_flag(ui_ContBody, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ContBody, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContBody, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContBody, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContBody, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContBody, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBody = lv_obj_create(ui_ContMain);
    lv_obj_set_width(ui_PanelBody, lv_pct(94));
    lv_obj_set_height(ui_PanelBody, lv_pct(80));
    lv_obj_set_x(ui_PanelBody, lv_pct(3));
    lv_obj_set_y(ui_PanelBody, lv_pct(22));
    lv_obj_set_scrollbar_mode(ui_PanelBody, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_PanelBody, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_PanelBody, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContCurWeather = lv_obj_create(ui_PanelBody);
    lv_obj_remove_style_all(ui_ContCurWeather);
    lv_obj_set_width(ui_ContCurWeather, lv_pct(100));
    lv_obj_set_height(ui_ContCurWeather, lv_pct(40));
    lv_obj_set_flex_flow(ui_ContCurWeather, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContCurWeather, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_ContCurWeather, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContCurWeather, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContCurWeather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContCurWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCurTemp = lv_label_create(ui_ContCurWeather);
    lv_obj_set_width(ui_LabelCurTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCurTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCurTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCurTemp, "10");
    lv_obj_set_style_text_font(ui_LabelCurTemp, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTodayWeather = lv_label_create(ui_ContCurWeather);
    lv_obj_set_width(ui_LabelTodayWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTodayWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTodayWeather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTodayWeather, "cloudy 22~26");

    ui_ContDaysWeather = lv_obj_create(ui_PanelBody);
    lv_obj_remove_style_all(ui_ContDaysWeather);
    lv_obj_set_width(ui_ContDaysWeather, lv_pct(100));
    lv_obj_set_height(ui_ContDaysWeather, lv_pct(50));
    lv_obj_set_x(ui_ContDaysWeather, lv_pct(0));
    lv_obj_set_y(ui_ContDaysWeather, lv_pct(45));
    lv_obj_set_flex_flow(ui_ContDaysWeather, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContDaysWeather, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_ContDaysWeather, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContDaysWeather, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContDaysWeather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContDaysWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContWeatherInfo1 = lv_obj_create(ui_ContDaysWeather);
    lv_obj_remove_style_all(ui_ContWeatherInfo1);
    lv_obj_set_width(ui_ContWeatherInfo1, lv_pct(100));
    lv_obj_set_height(ui_ContWeatherInfo1, lv_pct(30));
    lv_obj_remove_flag(ui_ContWeatherInfo1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDate1 = lv_label_create(ui_ContWeatherInfo1);
    lv_obj_set_width(ui_LabelDate1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate1, lv_pct(2));
    lv_obj_set_y(ui_LabelDate1, lv_pct(0));
    lv_obj_set_align(ui_LabelDate1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelDate1, "12/20 today");

    ui_ImgWeather1 = lv_image_create(ui_ContWeatherInfo1);
    lv_image_set_src(ui_ImgWeather1, &ui_img_cloudy_png);
    lv_obj_set_width(ui_ImgWeather1, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_ImgWeather1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_ImgWeather1, lv_pct(10));
    lv_obj_set_y(ui_ImgWeather1, lv_pct(0));
    lv_obj_set_align(ui_ImgWeather1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWeather1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImgWeather1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_scale(ui_ImgWeather1, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPrecip1 = lv_label_create(ui_ContWeatherInfo1);
    lv_obj_set_width(ui_LabelPrecip1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPrecip1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPrecip1, lv_pct(-21));
    lv_obj_set_y(ui_LabelPrecip1, lv_pct(0));
    lv_obj_set_align(ui_LabelPrecip1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelPrecip1, "");
    lv_obj_set_style_text_color(ui_LabelPrecip1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPrecip1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPrecip1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTodayTemp1 = lv_label_create(ui_ContWeatherInfo1);
    lv_obj_set_width(ui_LabelTodayTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTodayTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTodayTemp1, lv_pct(-2));
    lv_obj_set_y(ui_LabelTodayTemp1, lv_pct(0));
    lv_obj_set_align(ui_LabelTodayTemp1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelTodayTemp1, "22~26");

    ui_ContWeatherInfo3 = lv_obj_create(ui_ContDaysWeather);
    lv_obj_remove_style_all(ui_ContWeatherInfo3);
    lv_obj_set_width(ui_ContWeatherInfo3, lv_pct(100));
    lv_obj_set_height(ui_ContWeatherInfo3, lv_pct(30));
    lv_obj_remove_flag(ui_ContWeatherInfo3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDate3 = lv_label_create(ui_ContWeatherInfo3);
    lv_obj_set_width(ui_LabelDate3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate3, lv_pct(2));
    lv_obj_set_y(ui_LabelDate3, lv_pct(0));
    lv_obj_set_align(ui_LabelDate3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelDate3, "12/21 tomorrow");

    ui_ImgWeather3 = lv_image_create(ui_ContWeatherInfo3);
    lv_image_set_src(ui_ImgWeather3, &ui_img_rain_l_png);
    lv_obj_set_width(ui_ImgWeather3, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_ImgWeather3, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_ImgWeather3, lv_pct(10));
    lv_obj_set_y(ui_ImgWeather3, lv_pct(0));
    lv_obj_set_align(ui_ImgWeather3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWeather3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImgWeather3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_scale(ui_ImgWeather3, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPrecip3 = lv_label_create(ui_ContWeatherInfo3);
    lv_obj_set_width(ui_LabelPrecip3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPrecip3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPrecip3, lv_pct(-21));
    lv_obj_set_y(ui_LabelPrecip3, lv_pct(0));
    lv_obj_set_align(ui_LabelPrecip3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelPrecip3, "");
    lv_obj_set_style_text_color(ui_LabelPrecip3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPrecip3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPrecip3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTodayTemp3 = lv_label_create(ui_ContWeatherInfo3);
    lv_obj_set_width(ui_LabelTodayTemp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTodayTemp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTodayTemp3, lv_pct(-2));
    lv_obj_set_y(ui_LabelTodayTemp3, lv_pct(0));
    lv_obj_set_align(ui_LabelTodayTemp3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelTodayTemp3, "8~16");

    ui_ContWeatherInfo4 = lv_obj_create(ui_ContDaysWeather);
    lv_obj_remove_style_all(ui_ContWeatherInfo4);
    lv_obj_set_width(ui_ContWeatherInfo4, lv_pct(100));
    lv_obj_set_height(ui_ContWeatherInfo4, lv_pct(30));
    lv_obj_remove_flag(ui_ContWeatherInfo4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDate4 = lv_label_create(ui_ContWeatherInfo4);
    lv_obj_set_width(ui_LabelDate4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate4, lv_pct(2));
    lv_obj_set_y(ui_LabelDate4, lv_pct(0));
    lv_obj_set_align(ui_LabelDate4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelDate4, "12/22 tt");

    ui_ImgWeather4 = lv_image_create(ui_ContWeatherInfo4);
    lv_image_set_src(ui_ImgWeather4, &ui_img_thunder_rain_png);
    lv_obj_set_width(ui_ImgWeather4, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_ImgWeather4, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_ImgWeather4, lv_pct(10));
    lv_obj_set_y(ui_ImgWeather4, lv_pct(0));
    lv_obj_set_align(ui_ImgWeather4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWeather4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImgWeather4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_scale(ui_ImgWeather4, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPrecip4 = lv_label_create(ui_ContWeatherInfo4);
    lv_obj_set_width(ui_LabelPrecip4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPrecip4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPrecip4, lv_pct(-21));
    lv_obj_set_y(ui_LabelPrecip4, lv_pct(0));
    lv_obj_set_align(ui_LabelPrecip4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelPrecip4, "");
    lv_obj_set_style_text_color(ui_LabelPrecip4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPrecip4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPrecip4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTodayTemp4 = lv_label_create(ui_ContWeatherInfo4);
    lv_obj_set_width(ui_LabelTodayTemp4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTodayTemp4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTodayTemp4, lv_pct(-2));
    lv_obj_set_y(ui_LabelTodayTemp4, lv_pct(0));
    lv_obj_set_align(ui_LabelTodayTemp4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelTodayTemp4, "-2~5");

    ui_ContDetailInfo = lv_obj_create(ui_PanelBody);
    lv_obj_remove_style_all(ui_ContDetailInfo);
    lv_obj_set_width(ui_ContDetailInfo, lv_pct(100));
    lv_obj_set_height(ui_ContDetailInfo, lv_pct(80));
    lv_obj_set_x(ui_ContDetailInfo, lv_pct(0));
    lv_obj_set_y(ui_ContDetailInfo, lv_pct(100));
    lv_obj_set_flex_flow(ui_ContDetailInfo, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ContDetailInfo, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_ContDetailInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContDetailInfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContDetailInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContDetailInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContRainFall = lv_obj_create(ui_ContDetailInfo);
    lv_obj_remove_style_all(ui_ContRainFall);
    lv_obj_set_width(ui_ContRainFall, lv_pct(40));
    lv_obj_set_height(ui_ContRainFall, lv_pct(45));
    lv_obj_set_x(ui_ContRainFall, lv_pct(4));
    lv_obj_set_y(ui_ContRainFall, lv_pct(0));
    lv_obj_set_flex_flow(ui_ContRainFall, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContRainFall, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_ContRainFall, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgRainfall = lv_image_create(ui_ContRainFall);
    lv_image_set_src(ui_ImgRainfall, &ui_img_rainfall_png);
    lv_obj_set_width(ui_ImgRainfall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgRainfall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgRainfall, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgRainfall, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImgRainfall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelRainfall = lv_label_create(ui_ContRainFall);
    lv_obj_set_width(ui_LabelRainfall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRainfall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelRainfall, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRainfall, "rainfall\n123.0mm");

    ui_ContHumidity = lv_obj_create(ui_ContDetailInfo);
    lv_obj_remove_style_all(ui_ContHumidity);
    lv_obj_set_width(ui_ContHumidity, lv_pct(40));
    lv_obj_set_height(ui_ContHumidity, lv_pct(45));
    lv_obj_set_x(ui_ContHumidity, lv_pct(4));
    lv_obj_set_y(ui_ContHumidity, lv_pct(0));
    lv_obj_set_flex_flow(ui_ContHumidity, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContHumidity, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_ContHumidity, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgHumidity = lv_image_create(ui_ContHumidity);
    lv_image_set_src(ui_ImgHumidity, &ui_img_humidity_png);
    lv_obj_set_width(ui_ImgHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgHumidity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgHumidity, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImgHumidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHumidity = lv_label_create(ui_ContHumidity);
    lv_obj_set_width(ui_LabelHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelHumidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumidity, "humidity\n76%");

    ui_ContWind = lv_obj_create(ui_ContDetailInfo);
    lv_obj_remove_style_all(ui_ContWind);
    lv_obj_set_width(ui_ContWind, lv_pct(40));
    lv_obj_set_height(ui_ContWind, lv_pct(45));
    lv_obj_set_x(ui_ContWind, lv_pct(4));
    lv_obj_set_y(ui_ContWind, lv_pct(0));
    lv_obj_set_flex_flow(ui_ContWind, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContWind, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_ContWind, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgWind = lv_image_create(ui_ContWind);
    lv_image_set_src(ui_ImgWind, &ui_img_wind_png);
    lv_obj_set_width(ui_ImgWind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgWind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgWind, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWind, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImgWind, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelWind = lv_label_create(ui_ContWind);
    lv_obj_set_width(ui_LabelWind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWind, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWind, "north wind\n3 scale");

    ui_ContWindSpeed = lv_obj_create(ui_ContDetailInfo);
    lv_obj_remove_style_all(ui_ContWindSpeed);
    lv_obj_set_width(ui_ContWindSpeed, lv_pct(40));
    lv_obj_set_height(ui_ContWindSpeed, lv_pct(45));
    lv_obj_set_x(ui_ContWindSpeed, lv_pct(4));
    lv_obj_set_y(ui_ContWindSpeed, lv_pct(0));
    lv_obj_set_flex_flow(ui_ContWindSpeed, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContWindSpeed, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_ContWindSpeed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgWindSpeed = lv_image_create(ui_ContWindSpeed);
    lv_image_set_src(ui_ImgWindSpeed, &ui_img_wind_speed_png);
    lv_obj_set_width(ui_ImgWindSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgWindSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgWindSpeed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWindSpeed, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImgWindSpeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelWindSpeed = lv_label_create(ui_ContWindSpeed);
    lv_obj_set_width(ui_LabelWindSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWindSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWindSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWindSpeed, "wind speed\n9.66km/h");

    
    ui_ScrWeather_Mask = lv_obj_create(ui_ContMain);
    lv_obj_remove_style_all(ui_ScrWeather_Mask);
    lv_obj_set_width(ui_ScrWeather_Mask, lv_pct(100));
    lv_obj_set_height(ui_ScrWeather_Mask, lv_pct(100));
    lv_obj_add_flag(ui_ScrWeather_Mask, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ScrWeather_Mask, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrWeather_Mask, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrWeather_Mask, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrWeather_Mask, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrWeather_Spinner = lv_spinner_create(ui_ScrWeather_Mask);
    //lv_spinner_set_anim_params(ui_ScrWeather_Spinner, 1000, 90);
    lv_obj_set_width(ui_ScrWeather_Spinner, lv_pct(25));
    lv_obj_set_height(ui_ScrWeather_Spinner, lv_pct(25));
    lv_obj_set_x(ui_ScrWeather_Spinner, lv_pct(0));
    lv_obj_set_y(ui_ScrWeather_Spinner, lv_pct(-5));
    lv_obj_set_align(ui_ScrWeather_Spinner, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ScrWeather_Spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_ScrWeather_Spinner, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_ScrWeather_Spinner, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ScrWeather_LabelResponseRes = lv_label_create(ui_ScrWeather_Mask);
    lv_obj_set_width(ui_ScrWeather_LabelResponseRes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrWeather_LabelResponseRes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrWeather_LabelResponseRes, lv_pct(0));
    lv_obj_set_y(ui_ScrWeather_LabelResponseRes, lv_pct(8));
    lv_obj_set_align(ui_ScrWeather_LabelResponseRes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrWeather_LabelResponseRes, "获取中...");
    lv_obj_set_style_text_color(ui_ScrWeather_LabelResponseRes, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrWeather_LabelResponseRes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrWeather_LabelResponseRes, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScrWeather_BtnExit, ui_event_ScrWeather_BtnExit, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrWeather_BtnReflush, ui_event_ScrWeather_BtnReflush, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrWeather_DdSelectCity, ui_event_ScrWeather_DdSelectCity, LV_EVENT_ALL, NULL);



    weatherHandle.isReflush = 1;
}

void ui_ScrWeather_screen_destroy(void)
{
    if(ui_ScrWeather) lv_obj_del(ui_ScrWeather);

    // NULL screen variables
    ui_ScrWeather = NULL;
    ui_ContMain = NULL;
    ui_ScrWeather_ContHeader = NULL;
    ui_ScrWeather_BtnExit = NULL;
    ui_ScrWeather_LabelExit = NULL;
    ui_ScrWeather_LabelTitle = NULL;
    ui_ScrWeather_BtnReflush = NULL;
    ui_ScrWeather_LabelReflush = NULL;
    ui_ContTools = NULL;
    ui_ScrWeather_DdSelectCity = NULL;
    ui_ContBody = NULL;
    ui_PanelBody = NULL;
    ui_ContCurWeather = NULL;
    ui_LabelCurTemp = NULL;
    ui_LabelTodayWeather = NULL;
    ui_ContDaysWeather = NULL;
    ui_ContWeatherInfo1 = NULL;
    ui_LabelDate1 = NULL;
    ui_ImgWeather1 = NULL;
    ui_LabelPrecip1 = NULL;
    ui_LabelTodayTemp1 = NULL;
    ui_ContWeatherInfo3 = NULL;
    ui_LabelDate3 = NULL;
    ui_ImgWeather3 = NULL;
    ui_LabelPrecip3 = NULL;
    ui_LabelTodayTemp3 = NULL;
    ui_ContWeatherInfo4 = NULL;
    ui_LabelDate4 = NULL;
    ui_ImgWeather4 = NULL;
    ui_LabelPrecip4 = NULL;
    ui_LabelTodayTemp4 = NULL;
    ui_ContDetailInfo = NULL;
    ui_ContRainFall = NULL;
    ui_ImgRainfall = NULL;
    ui_LabelRainfall = NULL;
    ui_ContHumidity = NULL;
    ui_ImgHumidity = NULL;
    ui_LabelHumidity = NULL;
    ui_ContWind = NULL;
    ui_ImgWind = NULL;
    ui_LabelWind = NULL;
    ui_ContWindSpeed = NULL;
    ui_ImgWindSpeed = NULL;
    ui_LabelWindSpeed = NULL;

}

void ui_ScrWeather_screen_relocalize(void)
{
    // label widgets on screen

}
