// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Mobile_Phone

#ifndef UI_SCRMAIN_H
#define UI_SCRMAIN_H

#ifdef __cplusplus
extern "C" {
#endif
#include"SquareLine/ui.h"


// SCREEN: ui_ScrMain
extern void ui_ScrMain_screen_init(void);
extern void ui_ScrMain_screen_destroy(void);
extern void ui_ScrMain_screen_relocalize(void);
extern lv_obj_t * ui_ScrMain;
extern lv_obj_t * ui_ScrMain_ContBody;
extern lv_obj_t * ui_ScrMain_ContSetting;
extern void ui_event_ScrMain_ImgBtnSetting(lv_event_t * e);
extern lv_obj_t * ui_ScrMain_ImgBtnSetting;
extern lv_obj_t * ui_ScrMain_LabelSetting;
extern lv_obj_t * ui_ScrMain_ContCalendar;
extern void ui_event_ScrMain_ImgBtnCalendar(lv_event_t * e);
extern lv_obj_t * ui_ScrMain_ImgBtnCalendar;
extern lv_obj_t * ui_ScrMain_LabelCalendar;
extern lv_obj_t * ui_ScrMain_ContWeather;
extern void ui_event_ScrMain_ImgBtnWeather(lv_event_t * e);
extern lv_obj_t * ui_ScrMain_ImgBtnWeather;
extern lv_obj_t * ui_ScrMain_LabelWeather;
extern lv_obj_t * ui_ScrMain_ContFe;
extern void ui_event_ScrMain_ImgBtnFe(lv_event_t * e);
extern lv_obj_t * ui_ScrMain_ImgBtnFe;
extern lv_obj_t * ui_ScrMain_LabelFe;
extern lv_obj_t * ui_ScrMain_ContAlbum;
extern void ui_event_ScrMain_ImgBtnAlbum(lv_event_t * e);
extern lv_obj_t * ui_ScrMain_ImgBtnAlbum;
extern lv_obj_t * ui_ScrMain_LabelAlbum;
extern lv_obj_t * ui_ScrMain_ContVedio;
extern void ui_event_ScrMain_ImgBtnVedio(lv_event_t * e);
extern lv_obj_t * ui_ScrMain_ImgBtnVedio;
extern lv_obj_t * ui_ScrMain_LabelVedio;
extern lv_obj_t * ui_ScrMain_ContMusic;
extern void ui_event_ScrMain_ImgBtnMusic(lv_event_t * e);
extern lv_obj_t * ui_ScrMain_ImgBtnMusic;
extern lv_obj_t * ui_ScrMain_LabelMusic;
extern lv_obj_t * ui_ScrMain_ContCamera;
extern void ui_event_ScrMain_ImgBtnCamera(lv_event_t * e);
extern lv_obj_t * ui_ScrMain_ImgBtnCamera;
extern lv_obj_t * ui_ScrMain_LabelCamera;
extern lv_obj_t * ui_ScrMain_ContAI;
extern void ui_event_ScrMain_ImgBtnAI(lv_event_t * e);
extern lv_obj_t * ui_ScrMain_ImgBtnAI;
extern lv_obj_t * ui_ScrMain_LabelAI;
extern lv_obj_t * ui_ScrMain_ContRec;
extern void ui_event_ScrMain_ImgBtnAI2(lv_event_t * e);
extern lv_obj_t * ui_ScrMain_ImgBtnAI2;
extern lv_obj_t * ui_ScrMain_LabelAI2;
extern lv_obj_t * ui_ScrMain_ContHeader;
extern lv_obj_t * ui_ScrMain_LabelTime;
extern lv_obj_t * ui_ScrMain_ContTools;
extern lv_obj_t * ui_ScrMain_LabelBlueTooth;
extern lv_obj_t * ui_ScrMain_LabelWifi;
extern lv_obj_t * ui_ScrMain_LabelBatteryNum;
extern lv_obj_t * ui_ScrMain_LabelBattery;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScrMain_LabelApp;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

