// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCRALBUMSHOW_H
#define UI_SCRALBUMSHOW_H

#ifdef __cplusplus
extern "C" {
#endif
#include"SquareLine/screens/ui_ScrAlbum.h"

// SCREEN: ui_ScrAlbumShow
extern void ui_ScrAlbumShow_screen_init(void);
extern void ui_ScrAlbumShow_screen_destroy(void);
extern void ui_ScrAlbumShow_screen_relocalize(void);
extern lv_obj_t * ui_ScrAlbumShow;
extern lv_obj_t * ui_ScrAlbumShow_ContMain;
extern lv_obj_t * ui_ScrAlbumShow_ContHeader;
extern void ui_event_ScrAlbumShow_BtnExit(lv_event_t * e);
extern lv_obj_t * ui_ScrAlbumShow_BtnExit;
extern lv_obj_t * ui_ScrAlbumShow_LabelExit;
extern lv_obj_t * ui_ScrAlbumShow_LabelTitle;
extern void ui_event_ScrAlbumShow_BtnInfo(lv_event_t * e);
extern lv_obj_t * ui_ScrAlbumShow_BtnInfo;
extern lv_obj_t * ui_ScrAlbumShow_LabelInfo;
extern lv_obj_t * ui_ScrAlbumShow_ContShowInfo;
extern lv_obj_t * ui_ScrAlbumShow_LabelShowInfo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

