// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCRVEDIO_H
#define UI_SCRVEDIO_H

#ifdef __cplusplus
extern "C" {
#endif
#include"../ui.h"

// SCREEN: ui_ScrVedio
extern void ui_ScrVedio_screen_init(void);
extern void ui_ScrVedio_screen_destroy(void);
extern void ui_ScrVedio_screen_relocalize(void);
extern lv_obj_t * ui_ScrVedio;
extern lv_obj_t * ui_ScrVedio_ContMain;
extern lv_obj_t * ui_ScrVedio_ContHeader;
extern void ui_event_ScrVedio_BtnExit(lv_event_t * e);
extern lv_obj_t * ui_ScrVedio_BtnExit;
extern lv_obj_t * ui_ScrVedio_Label1;
extern lv_obj_t * ui_ScrVedio_LabelTitle;
extern lv_obj_t * ui_ScrVedio_PanelBody;
extern lv_obj_t * ui_ScrVedio_ContVedio;
extern void ui_event_ScrVedio_BtnVedio(lv_event_t * e);
extern lv_obj_t * ui_ScrVedio_BtnVedio;
extern lv_obj_t * ui_ScrVedio_LabelVedioSymbol;
extern lv_obj_t * ui_ScrVedio_LabelVedioName;
extern lv_obj_t* ui_ScrVedio_Table;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

