// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCRALBUM_H
#define UI_SCRALBUM_H

#ifdef __cplusplus
extern "C" {
#endif
#include"../ui.h"
// SCREEN: ui_ScrAlbum
extern void ui_ScrAlbum_screen_init(void);
extern void ui_ScrAlbum_screen_destroy(void);
extern void ui_ScrAlbum_screen_relocalize(void);
extern lv_obj_t * ui_ScrAlbum;
extern lv_obj_t * ui_ScrAlbum_ContMain;
extern lv_obj_t * ui_ScrAlbum_ContHeader;
extern void ui_event_ScrAlbum_BtnExit(lv_event_t * e);
extern lv_obj_t * ui_ScrAlbum_BtnExit;
extern lv_obj_t * ui_ScrAlbum_Label3;
extern lv_obj_t * ui_ScrAlbum_LabelTitle;
extern lv_obj_t * ui_ScrAlbum_PanelBody;
extern lv_obj_t * ui_ScrAlbum_ContImg;
extern void ui_event_ScrAlbum_BtnImg(lv_event_t * e);
extern lv_obj_t * ui_ScrAlbum_BtnImg;
extern lv_obj_t * ui_ScrAlbum_LabelImgSymbol;
extern lv_obj_t * ui_ScrAlbum_LabelImgName;
extern lv_obj_t* ui_ScrAlbum_Table;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

