// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCRAI_H
#define UI_SCRAI_H

#ifdef __cplusplus
extern "C" {
#endif
#include"../ui.h"

// SCREEN: ui_ScrAI
extern void ui_ScrAI_screen_init(void);
extern void ui_ScrAI_screen_destroy(void);
extern void ui_ScrAI_screen_relocalize(void);
extern lv_obj_t * ui_ScrAI;
extern lv_obj_t * ui_ScrAI_ContMain;
extern lv_obj_t * ui_ScrAI_ContHeader;
extern void ui_event_ScrAI_BtnExit(lv_event_t * e);
extern lv_obj_t * ui_ScrAI_BtnExit;
extern lv_obj_t * ui_ScrAI_Label2;
extern lv_obj_t* ui_ScrAI_Dropdown;
extern lv_obj_t * ui_ScrAI_LabelTitle;
extern lv_obj_t * ui_ScrAI_PanelBody;
extern lv_obj_t * ui_ScrAI_LabeSendDialog1;
extern lv_obj_t * ui_ScrAI_LabeAIDialog1;
extern lv_obj_t * ui_ScrAI_ContSend;
extern void ui_event_ScrAI_TextArea(lv_event_t * e);
extern lv_obj_t * ui_ScrAI_TextArea;
extern lv_obj_t * ui_ScrAI_BtnSend;
extern lv_obj_t * ui_ScrAI_LabelSend;
extern void ui_event_ScrAI_Keyboard(lv_event_t * e);
extern lv_obj_t * ui_ScrAI_Keyboard;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

