// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Mobile_Phone

#include "../ui.h"

lv_obj_t * ui_ScrMusic = NULL;
lv_obj_t * ui_ScrMusic_ContHeader = NULL;
lv_obj_t * ui_ScrMusic_BtnExit = NULL;
lv_obj_t * ui_ScrMusic_LabelExit = NULL;
lv_obj_t * ui_ScrMusic_LabelTitle = NULL;
lv_obj_t * ui_ScrMusic_TA_IP = NULL;
lv_obj_t * ui_ScrMusic_BtnConn = NULL;
lv_obj_t * ui_ScrMusic_LabelConn = NULL;
lv_obj_t * ui_ScrMusic_ContBody = NULL;
lv_obj_t * ui_ScrMusic_TabView = NULL;
lv_obj_t * ui_ScrMusic_TabPageSongList = NULL;
lv_obj_t * ui_ScrMusic_TabPageDisp = NULL;
lv_obj_t * ui_ScrMusic_ContDisp = NULL;
lv_obj_t * ui_ScrMusic_Image1 = NULL;
lv_obj_t * ui_ScrMusic_SliderVolume1 = NULL;
lv_obj_t * ui_ScrMusic_SliderVolume2 = NULL;
lv_obj_t * ui_ScrMusic_LabelSongName = NULL;
lv_obj_t * ui_ScrMusic_LabelAllVolNum = NULL;
lv_obj_t * ui_ScrMusic_ContSlider = NULL;
lv_obj_t * ui_ScrMusic_Slider = NULL;
lv_obj_t * ui_ScrMusic_LabelSongDuration = NULL;
lv_obj_t * ui_ScrMusic_ContPlayCtl = NULL;
lv_obj_t * ui_ScrMusic_BtnPlayMode = NULL;
lv_obj_t * ui_ScrMusic_LabelPlayMode = NULL;
lv_obj_t * ui_ScrMusic_BtnPrev = NULL;
lv_obj_t * ui_ScrMusic_LabelPrev = NULL;
lv_obj_t * ui_ScrMusic_BtnPlay = NULL;
lv_obj_t * ui_ScrMusic_LabelPlay = NULL;
lv_obj_t * ui_ScrMusic_BtnNext = NULL;
lv_obj_t * ui_ScrMusic_LabelNext = NULL;
lv_obj_t * ui_ScrMusic_ContDialog = NULL;
lv_obj_t * ui_ScrMusic_DialogLabelMain = NULL;
lv_obj_t * ui_ScrMusic_DialogBtnYes = NULL;
lv_obj_t * ui_ScrMusic_DialogLabelYes = NULL;
lv_obj_t * ui_ScrMusic_DialogBtnNo = NULL;
lv_obj_t * ui_ScrMusic_DialogLabelNo = NULL;
lv_obj_t * ui_ScrMusic_ContConnInfo = NULL;
lv_obj_t * ui_ScrMusic_ConInfoBtnOk = NULL;
lv_obj_t * ui_ScrMusic_ConInfoLabelOK = NULL;
lv_obj_t * ui_ScrMusic_ConInfoLabel = NULL;
lv_obj_t * ui_ScrMusic_ConInfoBar = NULL;
lv_obj_t * ui_ScrMusic_Keyboard = NULL;
// event funtions
void ui_event_ScrMusic_BtnExit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED)
    {
        musicHandle.isDeInit = 1;
        _ui_screen_change(&ui_ScrMain,&ui_ScrMusic,LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrMain_screen_init);
    }
}

void ui_event_ScrMusic_TA_IP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_keyboard_set_target(ui_ScrMusic_Keyboard,  ui_ScrMusic_TA_IP);
        _ui_flag_modify(ui_ScrMusic_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_ScrMusic_BtnConn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_flag_modify(ui_ScrMusic_ContConnInfo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        scr_music_btn_connect(e);
    }
}

void ui_event_ScrMusic_SliderVolume1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        scr_music_slider_vol1_cb(e);
    }
}

void ui_event_ScrMusic_SliderVolume2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        scr_music_slider_vol2_cb(e);
    }
}

void ui_event_ScrMusic_Slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        scr_music_slider_cb(e);
    }
}

void ui_event_ScrMusic_BtnPlayMode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scr_music_btn_play_mode_cb(e);
    }
}

void ui_event_ScrMusic_BtnPrev(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scr_music_btn_prev_cb(e);
    }
}

void ui_event_ScrMusic_BtnPlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scr_music_btn_play_cb(e);
    }
}

void ui_event_ScrMusic_BtnNext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scr_music_btn_next_cb(e);
    }
}

void ui_event_ScrMusic_DialogBtnYes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scr_music_dialog_btn_yes(e);
        _ui_flag_modify(ui_ScrMusic_ContDialog, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScrMusic_DialogBtnNo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ScrMusic_ContDialog, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScrMusic_ConInfoBtnOk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_flag_modify(ui_ScrMusic_ContConnInfo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScrMusic_Keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_ScrMusic_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_ScrMusic_screen_init(void)
{
    ui_ScrMusic = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_ScrMusic, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_ScrMusic_screen_destroy);

    ui_ScrMusic_ContHeader = lv_obj_create(ui_ScrMusic);
    lv_obj_remove_style_all(ui_ScrMusic_ContHeader);
    lv_obj_set_width(ui_ScrMusic_ContHeader, lv_pct(100));
    lv_obj_set_height(ui_ScrMusic_ContHeader, lv_pct(10));
    lv_obj_remove_flag(ui_ScrMusic_ContHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrMusic_ContHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_ContHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScrMusic_ContHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrMusic_ContHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrMusic_ContHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScrMusic_ContHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ScrMusic_ContHeader, lv_color_hex(0xEEEAEE), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_ContHeader, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ScrMusic_BtnExit = lv_button_create(ui_ScrMusic_ContHeader);
    lv_obj_set_height(ui_ScrMusic_BtnExit, lv_pct(100));
    lv_obj_set_width(ui_ScrMusic_BtnExit, LV_SIZE_CONTENT);   /// 15
    lv_obj_add_flag(ui_ScrMusic_BtnExit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrMusic_BtnExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrMusic_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrMusic_BtnExit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrMusic_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrMusic_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_LabelExit = lv_label_create(ui_ScrMusic_BtnExit);
    lv_obj_set_width(ui_ScrMusic_LabelExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMusic_LabelExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrMusic_LabelExit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrMusic_LabelExit, LV_SYMBOL_LEFT);
    lv_obj_set_style_text_color(ui_ScrMusic_LabelExit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrMusic_LabelExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMusic_LabelExit, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_ScrMusic_LabelTitle = lv_label_create(ui_ScrMusic_ContHeader);
    //lv_obj_set_width(ui_ScrMusic_LabelTitle, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_ScrMusic_LabelTitle, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_align(ui_ScrMusic_LabelTitle, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_ScrMusic_LabelTitle, "音乐");
    //lv_obj_set_style_text_font(ui_ScrMusic_LabelTitle, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_TA_IP = lv_textarea_create(ui_ScrMusic_ContHeader);
    lv_obj_set_width(ui_ScrMusic_TA_IP, lv_pct(50));
    lv_obj_set_height(ui_ScrMusic_TA_IP, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_ScrMusic_TA_IP, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_ScrMusic_TA_IP, "192.168.1.3");
    lv_textarea_set_placeholder_text(ui_ScrMusic_TA_IP, "输入服务端IP地址");
    lv_textarea_set_one_line(ui_ScrMusic_TA_IP, true);
    lv_obj_set_style_border_width(ui_ScrMusic_TA_IP, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_BtnConn = lv_button_create(ui_ScrMusic_ContHeader);
    lv_obj_set_height(ui_ScrMusic_BtnConn, lv_pct(100));
    lv_obj_set_width(ui_ScrMusic_BtnConn, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_align(ui_ScrMusic_BtnConn, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ScrMusic_BtnConn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrMusic_BtnConn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrMusic_BtnConn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrMusic_BtnConn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_BtnConn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrMusic_BtnConn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrMusic_BtnConn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_LabelConn = lv_label_create(ui_ScrMusic_BtnConn);
    lv_obj_set_width(ui_ScrMusic_LabelConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMusic_LabelConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrMusic_LabelConn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrMusic_LabelConn, "连接");
    lv_obj_set_style_text_color(ui_ScrMusic_LabelConn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrMusic_LabelConn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMusic_LabelConn, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_ContBody = lv_obj_create(ui_ScrMusic);
    lv_obj_remove_style_all(ui_ScrMusic_ContBody);
    lv_obj_set_width(ui_ScrMusic_ContBody, lv_pct(100));
    lv_obj_set_height(ui_ScrMusic_ContBody, lv_pct(90));
    lv_obj_set_x(ui_ScrMusic_ContBody, lv_pct(0));
    lv_obj_set_y(ui_ScrMusic_ContBody, lv_pct(10));
    lv_obj_remove_flag(ui_ScrMusic_ContBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_ScrMusic_ContBody, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_ContBody, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ScrMusic_TabView = lv_tabview_create(ui_ScrMusic_ContBody);
    lv_tabview_set_tab_bar_size(ui_ScrMusic_TabView, 25);
    lv_obj_set_width(ui_ScrMusic_TabView, lv_pct(100));
    lv_obj_set_height(ui_ScrMusic_TabView, lv_pct(100));
    lv_obj_set_x(ui_ScrMusic_TabView, 1);
    lv_obj_set_y(ui_ScrMusic_TabView, lv_pct(0));
    lv_obj_remove_flag(ui_ScrMusic_TabView, LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrMusic_TabView, lv_color_hex(0xF7F7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_TabView, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_TabPageSongList = lv_tabview_add_tab(ui_ScrMusic_TabView, "歌曲列表");
    lv_obj_set_flex_flow(ui_ScrMusic_TabPageSongList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScrMusic_TabPageSongList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_set_scroll_dir(ui_ScrMusic_TabPageSongList, LV_DIR_VER);
    lv_obj_set_style_pad_left(ui_ScrMusic_TabPageSongList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScrMusic_TabPageSongList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScrMusic_TabPageSongList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScrMusic_TabPageSongList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_TabPageDisp = lv_tabview_add_tab(ui_ScrMusic_TabView, "歌曲展示");
    lv_obj_set_scroll_dir(ui_ScrMusic_TabPageDisp, LV_DIR_VER);

    ui_ScrMusic_ContDisp = lv_obj_create(ui_ScrMusic_TabPageDisp);
    lv_obj_remove_style_all(ui_ScrMusic_ContDisp);
    lv_obj_set_width(ui_ScrMusic_ContDisp, lv_pct(100));
    lv_obj_set_height(ui_ScrMusic_ContDisp, lv_pct(80));
    lv_obj_remove_flag(ui_ScrMusic_ContDisp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_main_stop(ui_ScrMusic_ContDisp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ScrMusic_ContDisp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScrMusic_ContDisp, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScrMusic_ContDisp, lv_color_hex(0xE7E7E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrMusic_ContDisp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrMusic_ContDisp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScrMusic_ContDisp, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_Image1 = lv_image_create(ui_ScrMusic_ContDisp);
    lv_obj_set_width(ui_ScrMusic_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMusic_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrMusic_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScrMusic_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ScrMusic_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMusic_SliderVolume1 = lv_slider_create(ui_ScrMusic_ContDisp);
    lv_slider_set_range(ui_ScrMusic_SliderVolume1, 0, 25);
    lv_slider_set_value(ui_ScrMusic_SliderVolume1, 5, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ScrMusic_SliderVolume1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ScrMusic_SliderVolume1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ScrMusic_SliderVolume1, lv_pct(80));
    lv_obj_set_height(ui_ScrMusic_SliderVolume1, lv_pct(2));
    lv_obj_set_x(ui_ScrMusic_SliderVolume1, lv_pct(0));
    lv_obj_set_y(ui_ScrMusic_SliderVolume1, lv_pct(5));
    lv_obj_set_align(ui_ScrMusic_SliderVolume1, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_ScrMusic_SliderVolume1, lv_color_hex(0xD3D3D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_SliderVolume1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ScrMusic_SliderVolume1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ScrMusic_SliderVolume1,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ScrMusic_SliderVolume1,
                                                                                  lv_obj_get_style_pad_right(ui_ScrMusic_SliderVolume1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ScrMusic_SliderVolume2 = lv_slider_create(ui_ScrMusic_ContDisp);
    lv_slider_set_range(ui_ScrMusic_SliderVolume2, 0, 25);
    lv_slider_set_value(ui_ScrMusic_SliderVolume2, 1, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ScrMusic_SliderVolume2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ScrMusic_SliderVolume2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ScrMusic_SliderVolume2, lv_pct(80));
    lv_obj_set_height(ui_ScrMusic_SliderVolume2, lv_pct(2));
    lv_obj_set_x(ui_ScrMusic_SliderVolume2, lv_pct(0));
    lv_obj_set_y(ui_ScrMusic_SliderVolume2, lv_pct(15));
    lv_obj_set_align(ui_ScrMusic_SliderVolume2, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_ScrMusic_SliderVolume2, lv_color_hex(0xD3D3D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_SliderVolume2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ScrMusic_SliderVolume2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ScrMusic_SliderVolume2,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ScrMusic_SliderVolume2,
                                                                                  lv_obj_get_style_pad_right(ui_ScrMusic_SliderVolume2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ScrMusic_LabelSongName = lv_label_create(ui_ScrMusic_ContDisp);
    lv_obj_set_width(ui_ScrMusic_LabelSongName, lv_pct(100));
    lv_obj_set_height(ui_ScrMusic_LabelSongName, lv_pct(10));
    lv_obj_set_align(ui_ScrMusic_LabelSongName, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_long_mode(ui_ScrMusic_LabelSongName, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_ScrMusic_LabelSongName, "");
    lv_obj_set_style_text_font(ui_ScrMusic_LabelSongName, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_LabelAllVolNum = lv_label_create(ui_ScrMusic_ContDisp);
    lv_obj_set_width(ui_ScrMusic_LabelAllVolNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMusic_LabelAllVolNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMusic_LabelAllVolNum, lv_pct(0));
    lv_obj_set_y(ui_ScrMusic_LabelAllVolNum, lv_pct(20));
    lv_label_set_text(ui_ScrMusic_LabelAllVolNum,
                      "总音量：5\n音量1：5，音量2：1。\n总音量=音量1 乘以 音量2");

    ui_ScrMusic_ContSlider = lv_obj_create(ui_ScrMusic_TabPageDisp);
    lv_obj_remove_style_all(ui_ScrMusic_ContSlider);
    lv_obj_set_width(ui_ScrMusic_ContSlider, lv_pct(100));
    lv_obj_set_height(ui_ScrMusic_ContSlider, lv_pct(10));
    lv_obj_set_x(ui_ScrMusic_ContSlider, lv_pct(0));
    lv_obj_set_y(ui_ScrMusic_ContSlider, lv_pct(80));
    lv_obj_remove_flag(ui_ScrMusic_ContSlider, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMusic_Slider = lv_slider_create(ui_ScrMusic_ContSlider);
    lv_slider_set_value(ui_ScrMusic_Slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ScrMusic_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_ScrMusic_Slider, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_ScrMusic_Slider, lv_pct(55));
    lv_obj_set_height(ui_ScrMusic_Slider, lv_pct(10));
    lv_obj_set_x(ui_ScrMusic_Slider, lv_pct(-5));
    lv_obj_set_y(ui_ScrMusic_Slider, lv_pct(0));
    lv_obj_set_align(ui_ScrMusic_Slider, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_ScrMusic_Slider, lv_color_hex(0xD3D3D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_Slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ScrMusic_Slider, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_Slider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ScrMusic_Slider, lv_color_hex(0x414141), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_Slider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ScrMusic_Slider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ScrMusic_Slider,
                                                                                                      lv_obj_get_style_pad_right(ui_ScrMusic_Slider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ScrMusic_LabelSongDuration = lv_label_create(ui_ScrMusic_ContSlider);
    lv_obj_set_width(ui_ScrMusic_LabelSongDuration, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMusic_LabelSongDuration, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrMusic_LabelSongDuration, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ScrMusic_LabelSongDuration, "00:00/00:00");
    lv_obj_set_style_text_font(ui_ScrMusic_LabelSongDuration, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_ContPlayCtl = lv_obj_create(ui_ScrMusic_TabPageDisp);
    lv_obj_remove_style_all(ui_ScrMusic_ContPlayCtl);
    lv_obj_set_width(ui_ScrMusic_ContPlayCtl, lv_pct(100));
    lv_obj_set_height(ui_ScrMusic_ContPlayCtl, lv_pct(10));
    lv_obj_set_x(ui_ScrMusic_ContPlayCtl, lv_pct(0));
    lv_obj_set_y(ui_ScrMusic_ContPlayCtl, lv_pct(90));
    lv_obj_remove_flag(ui_ScrMusic_ContPlayCtl, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMusic_BtnPlayMode = lv_button_create(ui_ScrMusic_ContPlayCtl);
    lv_obj_set_width(ui_ScrMusic_BtnPlayMode, lv_pct(20));
    lv_obj_set_height(ui_ScrMusic_BtnPlayMode, lv_pct(70));
    lv_obj_set_align(ui_ScrMusic_BtnPlayMode, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ScrMusic_BtnPlayMode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrMusic_BtnPlayMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrMusic_BtnPlayMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrMusic_BtnPlayMode, lv_color_hex(0xEEEAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_BtnPlayMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrMusic_BtnPlayMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrMusic_BtnPlayMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrMusic_BtnPlayMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_LabelPlayMode = lv_label_create(ui_ScrMusic_BtnPlayMode);
    lv_obj_set_width(ui_ScrMusic_LabelPlayMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMusic_LabelPlayMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrMusic_LabelPlayMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrMusic_LabelPlayMode, "模式");
    lv_obj_set_style_text_color(ui_ScrMusic_LabelPlayMode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrMusic_LabelPlayMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMusic_LabelPlayMode, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_BtnPrev = lv_button_create(ui_ScrMusic_ContPlayCtl);
    lv_obj_set_width(ui_ScrMusic_BtnPrev, lv_pct(20));
    lv_obj_set_height(ui_ScrMusic_BtnPrev, lv_pct(70));
    lv_obj_set_x(ui_ScrMusic_BtnPrev, lv_pct(25));
    lv_obj_set_y(ui_ScrMusic_BtnPrev, lv_pct(0));
    lv_obj_set_align(ui_ScrMusic_BtnPrev, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ScrMusic_BtnPrev, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrMusic_BtnPrev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrMusic_BtnPrev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrMusic_BtnPrev, lv_color_hex(0xEEEAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_BtnPrev, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrMusic_BtnPrev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrMusic_BtnPrev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrMusic_BtnPrev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_LabelPrev = lv_label_create(ui_ScrMusic_BtnPrev);
    lv_obj_set_width(ui_ScrMusic_LabelPrev, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMusic_LabelPrev, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrMusic_LabelPrev, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrMusic_LabelPrev, LV_SYMBOL_PREV);
    lv_obj_set_style_text_color(ui_ScrMusic_LabelPrev, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrMusic_LabelPrev, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMusic_LabelPrev, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_BtnPlay = lv_button_create(ui_ScrMusic_ContPlayCtl);
    lv_obj_set_state(ui_ScrMusic_BtnPlay, LV_STATE_DISABLED, true);
    lv_obj_set_width(ui_ScrMusic_BtnPlay, lv_pct(20));
    lv_obj_set_height(ui_ScrMusic_BtnPlay, lv_pct(70));
    lv_obj_set_x(ui_ScrMusic_BtnPlay, lv_pct(50));
    lv_obj_set_y(ui_ScrMusic_BtnPlay, lv_pct(0));
    lv_obj_set_align(ui_ScrMusic_BtnPlay, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ScrMusic_BtnPlay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrMusic_BtnPlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrMusic_BtnPlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrMusic_BtnPlay, lv_color_hex(0xEEEAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_BtnPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrMusic_BtnPlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrMusic_BtnPlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrMusic_BtnPlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_LabelPlay = lv_label_create(ui_ScrMusic_BtnPlay);
    lv_obj_set_width(ui_ScrMusic_LabelPlay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMusic_LabelPlay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrMusic_LabelPlay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrMusic_LabelPlay, LV_SYMBOL_PLAY);
    lv_obj_set_style_text_color(ui_ScrMusic_LabelPlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrMusic_LabelPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMusic_LabelPlay, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrMusic_LabelPlay, lv_color_hex(0xEEEAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_LabelPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_BtnNext = lv_button_create(ui_ScrMusic_ContPlayCtl);
    lv_obj_set_width(ui_ScrMusic_BtnNext, lv_pct(20));
    lv_obj_set_height(ui_ScrMusic_BtnNext, lv_pct(70));
    lv_obj_set_x(ui_ScrMusic_BtnNext, lv_pct(75));
    lv_obj_set_y(ui_ScrMusic_BtnNext, lv_pct(0));
    lv_obj_set_align(ui_ScrMusic_BtnNext, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ScrMusic_BtnNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrMusic_BtnNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrMusic_BtnNext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrMusic_BtnNext, lv_color_hex(0xEEEAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_BtnNext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrMusic_BtnNext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrMusic_BtnNext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrMusic_BtnNext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_LabelNext = lv_label_create(ui_ScrMusic_BtnNext);
    lv_obj_set_width(ui_ScrMusic_LabelNext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMusic_LabelNext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMusic_LabelNext, lv_pct(20));
    lv_obj_set_y(ui_ScrMusic_LabelNext, lv_pct(0));
    lv_obj_set_align(ui_ScrMusic_LabelNext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrMusic_LabelNext, LV_SYMBOL_NEXT);
    lv_obj_set_style_text_color(ui_ScrMusic_LabelNext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrMusic_LabelNext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMusic_LabelNext, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_ContDialog = lv_obj_create(ui_ScrMusic);
    lv_obj_remove_style_all(ui_ScrMusic_ContDialog);
    lv_obj_set_width(ui_ScrMusic_ContDialog, lv_pct(80));
    lv_obj_set_height(ui_ScrMusic_ContDialog, lv_pct(40));
    lv_obj_set_x(ui_ScrMusic_ContDialog, lv_pct(0));
    lv_obj_set_y(ui_ScrMusic_ContDialog, lv_pct(-10));
    lv_obj_set_align(ui_ScrMusic_ContDialog, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScrMusic_ContDialog, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ScrMusic_ContDialog, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrMusic_ContDialog, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrMusic_ContDialog, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_ContDialog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScrMusic_ContDialog, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrMusic_ContDialog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrMusic_ContDialog, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_DialogLabelMain = lv_label_create(ui_ScrMusic_ContDialog);
    lv_obj_set_width(ui_ScrMusic_DialogLabelMain, lv_pct(90));
    lv_obj_set_height(ui_ScrMusic_DialogLabelMain, lv_pct(50));
    lv_obj_set_x(ui_ScrMusic_DialogLabelMain, lv_pct(5));
    lv_obj_set_y(ui_ScrMusic_DialogLabelMain, lv_pct(10));
    lv_label_set_text(ui_ScrMusic_DialogLabelMain, "Is Music XXXXXX delete");

    ui_ScrMusic_DialogBtnYes = lv_button_create(ui_ScrMusic_ContDialog);
    lv_obj_set_width(ui_ScrMusic_DialogBtnYes, lv_pct(30));
    lv_obj_set_height(ui_ScrMusic_DialogBtnYes, lv_pct(20));
    lv_obj_set_x(ui_ScrMusic_DialogBtnYes, lv_pct(10));
    lv_obj_set_y(ui_ScrMusic_DialogBtnYes, lv_pct(-10));
    lv_obj_set_align(ui_ScrMusic_DialogBtnYes, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_ScrMusic_DialogBtnYes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrMusic_DialogBtnYes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMusic_DialogLabelYes = lv_label_create(ui_ScrMusic_DialogBtnYes);
    lv_obj_set_width(ui_ScrMusic_DialogLabelYes, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_ScrMusic_DialogLabelYes, LV_SIZE_CONTENT);    /// 7
    lv_obj_set_align(ui_ScrMusic_DialogLabelYes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrMusic_DialogLabelYes, "确定");
    lv_obj_set_style_text_color(ui_ScrMusic_DialogLabelYes, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrMusic_DialogLabelYes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_DialogBtnNo = lv_button_create(ui_ScrMusic_ContDialog);
    lv_obj_set_width(ui_ScrMusic_DialogBtnNo, lv_pct(30));
    lv_obj_set_height(ui_ScrMusic_DialogBtnNo, lv_pct(20));
    lv_obj_set_x(ui_ScrMusic_DialogBtnNo, lv_pct(-10));
    lv_obj_set_y(ui_ScrMusic_DialogBtnNo, lv_pct(-10));
    lv_obj_set_align(ui_ScrMusic_DialogBtnNo, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_ScrMusic_DialogBtnNo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrMusic_DialogBtnNo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMusic_DialogLabelNo = lv_label_create(ui_ScrMusic_DialogBtnNo);
    lv_obj_set_width(ui_ScrMusic_DialogLabelNo, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_ScrMusic_DialogLabelNo, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_ScrMusic_DialogLabelNo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrMusic_DialogLabelNo, "取消");
    lv_obj_set_style_text_color(ui_ScrMusic_DialogLabelNo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrMusic_DialogLabelNo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_ContConnInfo = lv_obj_create(ui_ScrMusic);
    lv_obj_remove_style_all(ui_ScrMusic_ContConnInfo);
    lv_obj_set_width(ui_ScrMusic_ContConnInfo, lv_pct(80));
    lv_obj_set_height(ui_ScrMusic_ContConnInfo, lv_pct(40));
    lv_obj_set_align(ui_ScrMusic_ContConnInfo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScrMusic_ContConnInfo, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ScrMusic_ContConnInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrMusic_ContConnInfo, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrMusic_ContConnInfo, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusic_ContConnInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScrMusic_ContConnInfo, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrMusic_ContConnInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrMusic_ContConnInfo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ScrMusic_ContConnInfo, lv_color_hex(0xC2BDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ScrMusic_ContConnInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrMusic_ContConnInfo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrMusic_ContConnInfo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_ScrMusic_ContConnInfo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_ScrMusic_ContConnInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrMusic_ConInfoBtnOk = lv_button_create(ui_ScrMusic_ContConnInfo);
    lv_obj_set_width(ui_ScrMusic_ConInfoBtnOk, lv_pct(35));
    lv_obj_set_height(ui_ScrMusic_ConInfoBtnOk, lv_pct(25));
    lv_obj_set_x(ui_ScrMusic_ConInfoBtnOk, lv_pct(0));
    lv_obj_set_y(ui_ScrMusic_ConInfoBtnOk, lv_pct(-5));
    lv_obj_set_align(ui_ScrMusic_ConInfoBtnOk, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ScrMusic_ConInfoBtnOk, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrMusic_ConInfoBtnOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrMusic_ConInfoLabelOK = lv_label_create(ui_ScrMusic_ConInfoBtnOk);
    lv_obj_set_width(ui_ScrMusic_ConInfoLabelOK, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMusic_ConInfoLabelOK, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrMusic_ConInfoLabelOK, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrMusic_ConInfoLabelOK, "完毕");

    ui_ScrMusic_ConInfoLabel = lv_label_create(ui_ScrMusic_ContConnInfo);
    lv_obj_set_width(ui_ScrMusic_ConInfoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrMusic_ConInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrMusic_ConInfoLabel, lv_pct(10));
    lv_obj_set_y(ui_ScrMusic_ConInfoLabel, lv_pct(-5));
    lv_obj_set_align(ui_ScrMusic_ConInfoLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ScrMusic_ConInfoLabel, "正在连接服务器...");

    ui_ScrMusic_ConInfoBar = lv_bar_create(ui_ScrMusic_ContConnInfo);
    lv_bar_set_value(ui_ScrMusic_ConInfoBar, 0, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_ScrMusic_ConInfoBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ScrMusic_ConInfoBar, lv_pct(90));
    lv_obj_set_height(ui_ScrMusic_ConInfoBar, lv_pct(5));
    lv_obj_set_x(ui_ScrMusic_ConInfoBar, lv_pct(0));
    lv_obj_set_y(ui_ScrMusic_ConInfoBar, lv_pct(10));
    lv_obj_set_align(ui_ScrMusic_ConInfoBar, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ScrMusic_ConInfoBar,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ScrMusic_ConInfoBar, lv_obj_get_style_pad_right(ui_ScrMusic_ConInfoBar,
                                                                                  LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ScrMusic_Keyboard = lv_keyboard_create(ui_ScrMusic);
    lv_obj_set_width(ui_ScrMusic_Keyboard, lv_pct(100));
    lv_obj_set_height(ui_ScrMusic_Keyboard, lv_pct(40));
    lv_obj_set_align(ui_ScrMusic_Keyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ScrMusic_Keyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_keyboard_set_mode(ui_ScrMusic_Keyboard, LV_KEYBOARD_MODE_NUMBER); /*数字模块*/

    lv_obj_add_event_cb(ui_ScrMusic_BtnExit, ui_event_ScrMusic_BtnExit, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMusic_TA_IP, ui_event_ScrMusic_TA_IP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMusic_BtnConn, ui_event_ScrMusic_BtnConn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMusic_SliderVolume1, ui_event_ScrMusic_SliderVolume1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMusic_SliderVolume2, ui_event_ScrMusic_SliderVolume2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMusic_Slider, ui_event_ScrMusic_Slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMusic_BtnPlayMode, ui_event_ScrMusic_BtnPlayMode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMusic_BtnPrev, ui_event_ScrMusic_BtnPrev, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMusic_BtnPlay, ui_event_ScrMusic_BtnPlay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMusic_BtnNext, ui_event_ScrMusic_BtnNext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMusic_DialogBtnYes, ui_event_ScrMusic_DialogBtnYes, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMusic_DialogBtnNo, ui_event_ScrMusic_DialogBtnNo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMusic_ConInfoBtnOk, ui_event_ScrMusic_ConInfoBtnOk, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_ScrMusic_Keyboard, ui_ScrMusic_TA_IP);
    lv_obj_add_event_cb(ui_ScrMusic_Keyboard, ui_event_ScrMusic_Keyboard, LV_EVENT_ALL, NULL);

    musicHandle.isInit = 1;
}

void ui_ScrMusic_screen_destroy(void)
{
    if(ui_ScrMusic) lv_obj_del(ui_ScrMusic);

    // NULL screen variables
    ui_ScrMusic = NULL;
    ui_ScrMusic_ContHeader = NULL;
    ui_ScrMusic_BtnExit = NULL;
    ui_ScrMusic_LabelExit = NULL;
    ui_ScrMusic_LabelTitle = NULL;
    ui_ScrMusic_TA_IP = NULL;
    ui_ScrMusic_BtnConn = NULL;
    ui_ScrMusic_LabelConn = NULL;
    ui_ScrMusic_ContBody = NULL;
    ui_ScrMusic_TabView = NULL;
    ui_ScrMusic_TabPageSongList = NULL;
    ui_ScrMusic_TabPageDisp = NULL;
    ui_ScrMusic_ContDisp = NULL;
    ui_ScrMusic_Image1 = NULL;
    ui_ScrMusic_SliderVolume1 = NULL;
    ui_ScrMusic_SliderVolume2 = NULL;
    ui_ScrMusic_LabelSongName = NULL;
    ui_ScrMusic_LabelAllVolNum = NULL;
    ui_ScrMusic_ContSlider = NULL;
    ui_ScrMusic_Slider = NULL;
    ui_ScrMusic_LabelSongDuration = NULL;
    ui_ScrMusic_ContPlayCtl = NULL;
    ui_ScrMusic_BtnPlayMode = NULL;
    ui_ScrMusic_LabelPlayMode = NULL;
    ui_ScrMusic_BtnPrev = NULL;
    ui_ScrMusic_LabelPrev = NULL;
    ui_ScrMusic_BtnPlay = NULL;
    ui_ScrMusic_LabelPlay = NULL;
    ui_ScrMusic_BtnNext = NULL;
    ui_ScrMusic_LabelNext = NULL;
    ui_ScrMusic_ContDialog = NULL;
    ui_ScrMusic_DialogLabelMain = NULL;
    ui_ScrMusic_DialogBtnYes = NULL;
    ui_ScrMusic_DialogLabelYes = NULL;
    ui_ScrMusic_DialogBtnNo = NULL;
    ui_ScrMusic_DialogLabelNo = NULL;
    ui_ScrMusic_ContConnInfo = NULL;
    ui_ScrMusic_ConInfoBtnOk = NULL;
    ui_ScrMusic_ConInfoLabelOK = NULL;
    ui_ScrMusic_ConInfoLabel = NULL;
    ui_ScrMusic_ConInfoBar = NULL;
    ui_ScrMusic_Keyboard = NULL;

}

void ui_ScrMusic_screen_relocalize(void)
{
    // label widgets on screen

}
