// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScrAlbum = NULL;
lv_obj_t * ui_ScrAlbum_ContMain = NULL;
lv_obj_t * ui_ScrAlbum_ContHeader = NULL;
lv_obj_t * ui_ScrAlbum_BtnExit = NULL;
lv_obj_t * ui_ScrAlbum_Label3 = NULL;
lv_obj_t * ui_ScrAlbum_LabelTitle = NULL;
lv_obj_t * ui_ScrAlbum_PanelBody = NULL;
lv_obj_t * ui_ScrAlbum_ContImg = NULL;
lv_obj_t * ui_ScrAlbum_BtnImg = NULL;
lv_obj_t * ui_ScrAlbum_LabelImgSymbol = NULL;
lv_obj_t * ui_ScrAlbum_LabelImgName = NULL;
lv_obj_t * ui_ScrAlbum_Table = NULL; /*自定义*/

// event funtions
void ui_event_ScrAlbum_BtnExit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrMain,&ui_ScrAlbum,LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrMain_screen_init);
    }
}

//void ui_event_ScrAlbum_BtnImg(lv_event_t * e)
//{
//    lv_event_code_t event_code = lv_event_get_code(e);
//
//    if(event_code == LV_EVENT_CLICKED)
//    {
//        /*因为在_ui_screen_change 函数里，这里的按钮会被销毁*/
//        lv_obj_t* btn = lv_event_get_target_obj(e);
//        lv_obj_t* contImg = lv_obj_get_parent(btn);
//
//        uint16_t index = lv_obj_get_index(contImg);
//        albumHandle.index = index;
//        printf("choose img index:%d\n", index);
//
//        _ui_screen_change(&ui_ScrAlbumShow,&ui_ScrAlbum,LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrAlbumShow_screen_init);
//       
//        albumHandle.isDispImg = 1; /*代表要开始显示图片了*/
//    }
//}


void ui_event_ScrAlbum_Table(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        uint32_t row = 0;
        uint32_t col = 0;
        lv_obj_t* table = (lv_obj_t*)lv_event_get_target(e);
        lv_table_get_selected_cell(table, &row, &col);
        const char* text = lv_table_get_cell_value(table, row, col);

        albumHandle.index =(uint16_t)row;
        printf("choose img index:%d\n", row);
        printf("table item text:%s\n", text + 3);

        _ui_screen_change(&ui_ScrAlbumShow,&ui_ScrAlbum,LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrAlbumShow_screen_init);
        albumHandle.isDispImg = 1; /*代表要开始显示图片了*/ 
    }
}




// build funtions

void ui_ScrAlbum_screen_init(void)
{
    ui_ScrAlbum = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrAlbum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_ScrAlbum, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_ScrAlbum_screen_destroy);

    ui_ScrAlbum_ContMain = lv_obj_create(ui_ScrAlbum);
    lv_obj_remove_style_all(ui_ScrAlbum_ContMain);
    lv_obj_set_width(ui_ScrAlbum_ContMain, lv_pct(100));
    lv_obj_set_height(ui_ScrAlbum_ContMain, lv_pct(100));
    lv_obj_remove_flag(ui_ScrAlbum_ContMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrAlbum_ContMain, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrAlbum_ContMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAlbum_ContHeader = lv_obj_create(ui_ScrAlbum_ContMain);
    lv_obj_remove_style_all(ui_ScrAlbum_ContHeader);
    lv_obj_set_width(ui_ScrAlbum_ContHeader, lv_pct(100));
    lv_obj_set_height(ui_ScrAlbum_ContHeader, lv_pct(10));
    lv_obj_remove_flag(ui_ScrAlbum_ContHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ScrAlbum_ContHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrAlbum_ContHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrAlbum_ContHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScrAlbum_ContHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAlbum_BtnExit = lv_button_create(ui_ScrAlbum_ContHeader);
    lv_obj_set_width(ui_ScrAlbum_BtnExit, lv_pct(15));
    lv_obj_set_height(ui_ScrAlbum_BtnExit, lv_pct(100));
    lv_obj_set_x(ui_ScrAlbum_BtnExit, lv_pct(2));
    lv_obj_set_y(ui_ScrAlbum_BtnExit, lv_pct(0));
    lv_obj_add_flag(ui_ScrAlbum_BtnExit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrAlbum_BtnExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrAlbum_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrAlbum_BtnExit, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrAlbum_BtnExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrAlbum_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrAlbum_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAlbum_Label3 = lv_label_create(ui_ScrAlbum_BtnExit);
    lv_obj_set_width(ui_ScrAlbum_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrAlbum_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrAlbum_Label3, lv_pct(2));
    lv_obj_set_y(ui_ScrAlbum_Label3, lv_pct(0));
    lv_obj_set_align(ui_ScrAlbum_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrAlbum_Label3, LV_SYMBOL_LEFT);
    lv_obj_set_style_text_color(ui_ScrAlbum_Label3, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrAlbum_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrAlbum_Label3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAlbum_LabelTitle = lv_label_create(ui_ScrAlbum_ContHeader);
    lv_obj_set_width(ui_ScrAlbum_LabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrAlbum_LabelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrAlbum_LabelTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrAlbum_LabelTitle, "Album");
    lv_obj_set_style_text_font(ui_ScrAlbum_LabelTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);


    /*表格显示相册的图片名*/
    ui_ScrAlbum_Table = lv_table_create(ui_ScrAlbum);
    lv_obj_set_size(ui_ScrAlbum_Table, lv_pct(100), lv_pct(90));
    lv_obj_set_align(ui_ScrAlbum_Table, LV_ALIGN_TOP_LEFT);
    lv_obj_set_pos(ui_ScrAlbum_Table, lv_pct(0), lv_pct(10));

    lv_table_set_column_width(ui_ScrAlbum_Table, 0, lv_pct(100));
    lv_table_set_column_count(ui_ScrAlbum_Table, 1);
    //lv_table_set_row_count(ui_ScrAlbum_Table, 30);

    lv_obj_add_event_cb(ui_ScrAlbum_Table, ui_event_ScrAlbum_Table, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrAlbum_BtnExit, ui_event_ScrAlbum_BtnExit, LV_EVENT_ALL, NULL);

    albumHandle.isInit = 1;
}

void ui_ScrAlbum_screen_destroy(void)
{
    if(ui_ScrAlbum) lv_obj_del(ui_ScrAlbum);

    // NULL screen variables
    ui_ScrAlbum = NULL;
    ui_ScrAlbum_ContMain = NULL;
    ui_ScrAlbum_ContHeader = NULL;
    ui_ScrAlbum_BtnExit = NULL;
    ui_ScrAlbum_Label3 = NULL;
    ui_ScrAlbum_LabelTitle = NULL;
    ui_ScrAlbum_PanelBody = NULL;
    ui_ScrAlbum_ContImg = NULL;
    ui_ScrAlbum_BtnImg = NULL;
    ui_ScrAlbum_LabelImgSymbol = NULL;
    ui_ScrAlbum_LabelImgName = NULL;
    ui_ScrAlbum_Table=NULL;
}

void ui_ScrAlbum_screen_relocalize(void)
{
    // label widgets on screen

}
