// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project
#include  "Squareline/screens/ui_ScrAI.h"

lv_obj_t * ui_ScrAI = NULL;
lv_obj_t * ui_ScrAI_ContMain = NULL;
lv_obj_t * ui_ScrAI_ContHeader = NULL;
lv_obj_t * ui_ScrAI_BtnExit = NULL;
lv_obj_t * ui_ScrAI_Label2 = NULL;
lv_obj_t* ui_ScrAI_Dropdown = NULL;
lv_obj_t * ui_ScrAI_LabelTitle = NULL;
lv_obj_t * ui_ScrAI_PanelBody = NULL;
lv_obj_t * ui_ScrAI_LabeSendDialog1 = NULL;
lv_obj_t * ui_ScrAI_LabeAIDialog1 = NULL;
lv_obj_t * ui_ScrAI_ContSend = NULL;
lv_obj_t * ui_ScrAI_TextArea = NULL;
lv_obj_t * ui_ScrAI_BtnSend = NULL;
lv_obj_t * ui_ScrAI_LabelSend = NULL;
lv_obj_t * ui_ScrAI_Keyboard = NULL;
// event funtions
void ui_event_ScrAI_BtnExit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrMain,&ui_ScrAI,LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrMain_screen_init);
    }
}

void ui_event_ScrAI_Dropdown(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED) {
        scr_ai_dropdown_event_cb(e);
    }
}

void ui_event_ScrAI_TextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_ScrAI_Keyboard,  ui_ScrAI_TextArea);
        _ui_flag_modify(ui_ScrAI_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_ScrAI_ContSend, _UI_BASIC_PROPERTY_POSITION_Y,  -130);
    }
}

void ui_event_ScrAI_Keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_basic_set_property(ui_ScrAI_ContSend, _UI_BASIC_PROPERTY_POSITION_Y,  0);
        _ui_flag_modify(ui_ScrAI_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScrAI_BtnSend(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        src_ai_btn_send_cb(e);
        _ui_flag_modify(ui_ScrAI_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_basic_set_property(ui_ScrAI_ContSend, _UI_BASIC_PROPERTY_POSITION_Y, 0);
    }
}


void ui_event_ScrAI_PanelBody(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_PRESSED) {
        _ui_basic_set_property(ui_ScrAI_ContSend, _UI_BASIC_PROPERTY_POSITION_Y, 0);
        _ui_flag_modify(ui_ScrAI_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_ScrAI_screen_init(void)
{
    ui_ScrAI = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrAI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrAI_ContMain = lv_obj_create(ui_ScrAI);
    lv_obj_remove_style_all(ui_ScrAI_ContMain);
    lv_obj_set_width(ui_ScrAI_ContMain, lv_pct(100));
    lv_obj_set_height(ui_ScrAI_ContMain, lv_pct(100));
    lv_obj_remove_flag(ui_ScrAI_ContMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrAI_ContMain, lv_color_hex(0xF7F7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrAI_ContMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAI_ContHeader = lv_obj_create(ui_ScrAI_ContMain);
    lv_obj_remove_style_all(ui_ScrAI_ContHeader);
    lv_obj_set_width(ui_ScrAI_ContHeader, lv_pct(100));
    lv_obj_set_height(ui_ScrAI_ContHeader, lv_pct(10));
    lv_obj_remove_flag(ui_ScrAI_ContHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ScrAI_ContHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrAI_ContHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrAI_ContHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScrAI_ContHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAI_BtnExit = lv_button_create(ui_ScrAI_ContHeader);
    lv_obj_set_width(ui_ScrAI_BtnExit, lv_pct(15));
    lv_obj_set_height(ui_ScrAI_BtnExit, lv_pct(100));
    lv_obj_set_x(ui_ScrAI_BtnExit, lv_pct(2));
    lv_obj_set_y(ui_ScrAI_BtnExit, lv_pct(0));
    lv_obj_add_flag(ui_ScrAI_BtnExit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrAI_BtnExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrAI_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrAI_BtnExit, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrAI_BtnExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrAI_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrAI_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAI_Label2 = lv_label_create(ui_ScrAI_BtnExit);
    lv_obj_set_width(ui_ScrAI_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrAI_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrAI_Label2, lv_pct(2));
    lv_obj_set_y(ui_ScrAI_Label2, lv_pct(0));
    lv_obj_set_align(ui_ScrAI_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrAI_Label2, "EX");
    lv_obj_set_style_text_color(ui_ScrAI_Label2, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrAI_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrAI_Label2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_ScrAI_Dropdown = lv_dropdown_create(ui_ScrAI_ContHeader);
    lv_dropdown_set_options(ui_ScrAI_Dropdown,
        "讯飞星火AI轻量级\n百度文心AI轻量级\n百度文心AI高性能\n百度文心AI超高性能");
    lv_obj_set_width(ui_ScrAI_Dropdown, lv_pct(70));
    lv_obj_set_height(ui_ScrAI_Dropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrAI_Dropdown, lv_pct(5));
    lv_obj_set_y(ui_ScrAI_Dropdown, lv_pct(0));
    lv_obj_set_align(ui_ScrAI_Dropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScrAI_Dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_align(ui_ScrAI_Dropdown, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrAI_Dropdown, &ui_font_show_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrAI_Dropdown, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrAI_Dropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrAI_Dropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_dropdown_get_list(ui_ScrAI_Dropdown), LV_TEXT_ALIGN_CENTER,
        LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ScrAI_Dropdown), &ui_font_show_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_ScrAI_LabelTitle = lv_label_create(ui_ScrAI_ContHeader);
    //lv_obj_set_width(ui_ScrAI_LabelTitle, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_ScrAI_LabelTitle, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_align(ui_ScrAI_LabelTitle, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_ScrAI_LabelTitle, "AI");
    //lv_obj_set_style_text_font(ui_ScrAI_LabelTitle, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAI_PanelBody = lv_obj_create(ui_ScrAI_ContMain);
    lv_obj_set_width(ui_ScrAI_PanelBody, lv_pct(96));
    lv_obj_set_height(ui_ScrAI_PanelBody, lv_pct(70));
    lv_obj_set_x(ui_ScrAI_PanelBody, lv_pct(2));
    lv_obj_set_y(ui_ScrAI_PanelBody, lv_pct(10));
    lv_obj_set_flex_flow(ui_ScrAI_PanelBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScrAI_PanelBody, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
    lv_obj_add_flag(ui_ScrAI_PanelBody, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ScrAI_PanelBody, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_ScrAI_PanelBody, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_ScrAI_PanelBody, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrAI_PanelBody, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrAI_PanelBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrAI_PanelBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrAI_PanelBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ScrAI_PanelBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScrAI_PanelBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScrAI_PanelBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScrAI_PanelBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    


    ui_ScrAI_ContSend = lv_obj_create(ui_ScrAI_ContMain);
    lv_obj_remove_style_all(ui_ScrAI_ContSend);
    lv_obj_set_width(ui_ScrAI_ContSend, lv_pct(100));
    lv_obj_set_height(ui_ScrAI_ContSend, lv_pct(20));
    lv_obj_set_align(ui_ScrAI_ContSend, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_ScrAI_ContSend, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrAI_TextArea = lv_textarea_create(ui_ScrAI_ContSend);
    lv_obj_set_width(ui_ScrAI_TextArea, lv_pct(80));
    lv_obj_set_height(ui_ScrAI_TextArea, lv_pct(70));
    lv_obj_set_x(ui_ScrAI_TextArea, lv_pct(2));
    lv_obj_set_y(ui_ScrAI_TextArea, lv_pct(15));
    lv_textarea_set_placeholder_text(ui_ScrAI_TextArea, "Placeholder...");
    lv_obj_set_style_shadow_color(ui_ScrAI_TextArea, lv_color_hex(0xE7E7E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ScrAI_TextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrAI_TextArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrAI_TextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_ScrAI_TextArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_ScrAI_TextArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrAI_TextArea, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrAI_BtnSend = lv_button_create(ui_ScrAI_ContSend);
    lv_obj_set_width(ui_ScrAI_BtnSend, lv_pct(14));
    lv_obj_set_height(ui_ScrAI_BtnSend, lv_pct(70));
    lv_obj_set_x(ui_ScrAI_BtnSend, lv_pct(-2));
    lv_obj_set_y(ui_ScrAI_BtnSend, lv_pct(-3));
    lv_obj_set_align(ui_ScrAI_BtnSend, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ScrAI_BtnSend, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrAI_BtnSend, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrAI_LabelSend = lv_label_create(ui_ScrAI_BtnSend);
    lv_obj_set_width(ui_ScrAI_LabelSend, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrAI_LabelSend, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrAI_LabelSend, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrAI_LabelSend, "send");
    lv_obj_set_style_text_color(ui_ScrAI_LabelSend, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrAI_LabelSend, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    /****键盘和拼音***/
    lv_obj_t* pinyin = lv_ime_pinyin_create(ui_ScrAI_ContMain);
    lv_obj_set_style_text_font(pinyin, &lv_font_montserrat_14, 0);

    ui_ScrAI_Keyboard = lv_keyboard_create(ui_ScrAI_ContMain);
    lv_obj_set_width(ui_ScrAI_Keyboard, lv_pct(100));
    lv_obj_set_height(ui_ScrAI_Keyboard, lv_pct(40));
    lv_obj_set_align(ui_ScrAI_Keyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ScrAI_Keyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_ime_pinyin_set_keyboard(pinyin, ui_ScrAI_Keyboard);
    lv_keyboard_set_textarea(ui_ScrAI_Keyboard, ui_ScrAI_TextArea);


    lv_obj_add_event_cb(ui_ScrAI_BtnExit, ui_event_ScrAI_BtnExit, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrAI_Dropdown, ui_event_ScrAI_Dropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrAI_TextArea, ui_event_ScrAI_TextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrAI_Keyboard, ui_event_ScrAI_Keyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrAI_BtnSend, ui_event_ScrAI_BtnSend, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrAI_PanelBody, ui_event_ScrAI_PanelBody, LV_EVENT_ALL, NULL);

}

void ui_ScrAI_screen_destroy(void)
{
    if(ui_ScrAI) lv_obj_del(ui_ScrAI);

    // NULL screen variables
    ui_ScrAI = NULL;
    ui_ScrAI_ContMain = NULL;
    ui_ScrAI_ContHeader = NULL;
    ui_ScrAI_BtnExit = NULL;
    ui_ScrAI_Label2 = NULL;
    ui_ScrAI_Dropdown = NULL;
    ui_ScrAI_LabelTitle = NULL;
    ui_ScrAI_PanelBody = NULL;
    ui_ScrAI_LabeSendDialog1 = NULL;
    ui_ScrAI_LabeAIDialog1 = NULL;
    ui_ScrAI_ContSend = NULL;
    ui_ScrAI_TextArea = NULL;
    ui_ScrAI_BtnSend = NULL;
    ui_ScrAI_LabelSend = NULL;
    ui_ScrAI_Keyboard = NULL;

}

void ui_ScrAI_screen_relocalize(void)
{
    // label widgets on screen

}
