// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Mobile_Phone

#ifndef UI_SCRMUSIC_H
#define UI_SCRMUSIC_H

#ifdef __cplusplus
extern "C" {
#endif
#include"SquareLine/ui.h"
// SCREEN: ui_ScrMusic
extern void ui_ScrMusic_screen_init(void);
extern void ui_ScrMusic_screen_destroy(void);
extern void ui_ScrMusic_screen_relocalize(void);
extern lv_obj_t * ui_ScrMusic;
extern lv_obj_t * ui_ScrMusic_ContHeader;
extern void ui_event_ScrMusic_BtnExit(lv_event_t * e);
extern lv_obj_t * ui_ScrMusic_BtnExit;
extern lv_obj_t * ui_ScrMusic_LabelExit;
extern lv_obj_t * ui_ScrMusic_LabelTitle;
extern void ui_event_ScrMusic_TA_IP(lv_event_t * e);
extern lv_obj_t * ui_ScrMusic_TA_IP;
extern void ui_event_ScrMusic_BtnConn(lv_event_t * e);
extern lv_obj_t * ui_ScrMusic_BtnConn;
extern lv_obj_t * ui_ScrMusic_LabelConn;
extern lv_obj_t * ui_ScrMusic_ContBody;
extern lv_obj_t * ui_ScrMusic_TabView;
extern lv_obj_t * ui_ScrMusic_TabPageSongList;
extern lv_obj_t * ui_ScrMusic_TabPageDisp;
extern lv_obj_t * ui_ScrMusic_ContDisp;
extern lv_obj_t * ui_ScrMusic_Image1;
extern void ui_event_ScrMusic_SliderVolume1(lv_event_t * e);
extern lv_obj_t * ui_ScrMusic_SliderVolume1;
extern void ui_event_ScrMusic_SliderVolume2(lv_event_t * e);
extern lv_obj_t * ui_ScrMusic_SliderVolume2;
extern lv_obj_t * ui_ScrMusic_LabelSongName;
extern lv_obj_t * ui_ScrMusic_LabelAllVolNum;
extern lv_obj_t * ui_ScrMusic_ContSlider;
extern void ui_event_ScrMusic_Slider(lv_event_t * e);
extern lv_obj_t * ui_ScrMusic_Slider;
extern lv_obj_t * ui_ScrMusic_LabelSongDuration;
extern lv_obj_t * ui_ScrMusic_ContPlayCtl;
extern void ui_event_ScrMusic_BtnPlayMode(lv_event_t * e);
extern lv_obj_t * ui_ScrMusic_BtnPlayMode;
extern lv_obj_t * ui_ScrMusic_LabelPlayMode;
extern void ui_event_ScrMusic_BtnPrev(lv_event_t * e);
extern lv_obj_t * ui_ScrMusic_BtnPrev;
extern lv_obj_t * ui_ScrMusic_LabelPrev;
extern void ui_event_ScrMusic_BtnPlay(lv_event_t * e);
extern lv_obj_t * ui_ScrMusic_BtnPlay;
extern lv_obj_t * ui_ScrMusic_LabelPlay;
extern void ui_event_ScrMusic_BtnNext(lv_event_t * e);
extern lv_obj_t * ui_ScrMusic_BtnNext;
extern lv_obj_t * ui_ScrMusic_LabelNext;
extern lv_obj_t * ui_ScrMusic_ContDialog;
extern lv_obj_t * ui_ScrMusic_DialogLabelMain;
extern void ui_event_ScrMusic_DialogBtnYes(lv_event_t * e);
extern lv_obj_t * ui_ScrMusic_DialogBtnYes;
extern lv_obj_t * ui_ScrMusic_DialogLabelYes;
extern void ui_event_ScrMusic_DialogBtnNo(lv_event_t * e);
extern lv_obj_t * ui_ScrMusic_DialogBtnNo;
extern lv_obj_t * ui_ScrMusic_DialogLabelNo;
extern lv_obj_t * ui_ScrMusic_ContConnInfo;
extern void ui_event_ScrMusic_ConInfoBtnOk(lv_event_t * e);
extern lv_obj_t * ui_ScrMusic_ConInfoBtnOk;
extern lv_obj_t * ui_ScrMusic_ConInfoLabelOK;
extern lv_obj_t * ui_ScrMusic_ConInfoLabel;
extern lv_obj_t * ui_ScrMusic_ConInfoBar;
extern void ui_event_ScrMusic_Keyboard(lv_event_t * e);
extern lv_obj_t * ui_ScrMusic_Keyboard;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

