// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Mobile_Phone

#ifndef UI_SCRREC_H
#define UI_SCRREC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrRec
extern void ui_ScrRec_screen_init(void);
extern void ui_ScrRec_screen_destroy(void);
extern void ui_ScrRec_screen_relocalize(void);
extern lv_obj_t * ui_ScrRec;
extern lv_obj_t * ui_ScrRec_ContHeader;
extern void ui_event_ScrRec_BtnExit(lv_event_t * e);
extern lv_obj_t * ui_ScrRec_BtnExit;
extern lv_obj_t * ui_ScrRec_LabelExit;
extern lv_obj_t * ui_ScrRec_LabelTitle;
extern lv_obj_t * ui_ScrRec_ContBody;
extern lv_obj_t * ui_ScrRec_ContProcess;
extern lv_obj_t * ui_ScrRec_Process;
extern lv_obj_t * ui_ScrRec_Process_Time;
extern lv_obj_t * ui_ScrRec_ProcessLabel;
extern lv_obj_t * ui_ScrRec_PrecessRecTime;
extern lv_obj_t * ui_ScrRec_ContFooter;
extern void ui_event_ScrRec_Btn_Play(lv_event_t * e);
extern lv_obj_t * ui_ScrRec_Btn_Play;
extern lv_obj_t * ui_ScrRec_LabelPlay;
extern void ui_event_ScrRec_Btn_Over(lv_event_t * e);
extern lv_obj_t * ui_ScrRec_Btn_Over;
extern lv_obj_t * ui_ScrRec_LabelOver;
extern void ui_event_ScrRec_Btn_Record(lv_event_t * e);
extern lv_obj_t * ui_ScrRec_Btn_Record;
extern lv_obj_t * ui_ScrRec_LabelRecord;
extern lv_obj_t * ui_ScrRec_ContDialog;
extern lv_obj_t * ui_ScrRec_DialogLabelMain;
extern void ui_event_ScrRec_DialogBtnYes(lv_event_t * e);
extern lv_obj_t * ui_ScrRec_DialogBtnYes;
extern lv_obj_t * ui_ScrRec_DialogLabelYes;
extern void ui_event_ScrRec_DialogBtnNo(lv_event_t * e);
extern lv_obj_t * ui_ScrRec_DialogBtnNo;
extern lv_obj_t * ui_ScrRec_DialogLabelNo;
extern void ui_event_ScrRec_SliderVolume(lv_event_t * e);
extern lv_obj_t * ui_ScrRec_SliderVolume;
extern lv_obj_t * ui_ScrRec_LabelVolume;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

