// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCRVEDIOSHOW_H
#define UI_SCRVEDIOSHOW_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrVedioShow
extern void ui_ScrVedioShow_screen_init(void);
extern void ui_ScrVedioShow_screen_destroy(void);
extern void ui_ScrVedioShow_screen_relocalize(void);
extern lv_obj_t * ui_ScrVedioShow;
extern void ui_event_ScrVedioShow_ContMain(lv_event_t * e);
extern lv_obj_t * ui_ScrVedioShow_ContMain;
extern lv_obj_t * ui_ScrVedioShow_ContHeader;
extern void ui_event_ScrVedioShow_BtnExit(lv_event_t * e);
extern lv_obj_t * ui_ScrVedioShow_BtnExit;
extern lv_obj_t * ui_ScrVedioShow_LabelExit;
extern lv_obj_t * ui_ScrVedioShow_LabelTitle;
extern lv_obj_t * ui_ScrVedioShow_ContFooter;
extern lv_obj_t * ui_ScrVedioShow_ContPlayCtl;
extern void ui_event_ScrVedioShow_BtnPrev(lv_event_t * e);
extern lv_obj_t * ui_ScrVedioShow_BtnPrev;
extern lv_obj_t * ui_ScrVedioShow_LabelPrev;
extern void ui_event_ScrVedioShow_BtnPlay(lv_event_t * e);
extern lv_obj_t * ui_ScrVedioShow_BtnPlay;
extern lv_obj_t * ui_ScrVedioShow_LabelPlay;
extern void ui_event_ScrVedioShow_BtnNext(lv_event_t * e);
extern lv_obj_t * ui_ScrVedioShow_BtnNext;
extern lv_obj_t * ui_ScrVedioShow_LabelNext;
extern void ui_event_ScrVedioShow_Slider(lv_event_t * e);
extern lv_obj_t * ui_ScrVedioShow_Slider;
extern lv_obj_t * ui_ScrVedioShow_ContVolume;
extern lv_obj_t * ui_ScrVedioShow_BarVolume;
extern lv_obj_t * ui_ScrVedioShow_LabelVolSymbol;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

