// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Mobile_Phone

#include "../ui.h"
#include"core/app_handles.h"

lv_obj_t * ui_ScrRec = NULL;
lv_obj_t * ui_ScrRec_ContHeader = NULL;
lv_obj_t * ui_ScrRec_BtnExit = NULL;
lv_obj_t * ui_ScrRec_LabelExit = NULL;
lv_obj_t * ui_ScrRec_LabelTitle = NULL;
lv_obj_t * ui_ScrRec_ContBody = NULL;
lv_obj_t * ui_ScrRec_ContProcess = NULL;
lv_obj_t * ui_ScrRec_Process = NULL;
lv_obj_t * ui_ScrRec_Process_Time = NULL;
lv_obj_t * ui_ScrRec_ProcessLabel = NULL;
lv_obj_t * ui_ScrRec_PrecessRecTime = NULL;
lv_obj_t * ui_ScrRec_ContFooter = NULL;
lv_obj_t * ui_ScrRec_Btn_Play = NULL;
lv_obj_t * ui_ScrRec_LabelPlay = NULL;
lv_obj_t * ui_ScrRec_Btn_Over = NULL;
lv_obj_t * ui_ScrRec_LabelOver = NULL;
lv_obj_t * ui_ScrRec_Btn_Record = NULL;
lv_obj_t * ui_ScrRec_LabelRecord = NULL;
lv_obj_t * ui_ScrRec_ContDialog = NULL;
lv_obj_t * ui_ScrRec_DialogLabelMain = NULL;
lv_obj_t * ui_ScrRec_DialogBtnYes = NULL;
lv_obj_t * ui_ScrRec_DialogLabelYes = NULL;
lv_obj_t * ui_ScrRec_DialogBtnNo = NULL;
lv_obj_t * ui_ScrRec_DialogLabelNo = NULL;
lv_obj_t * ui_ScrRec_SliderVolume = NULL;
lv_obj_t * ui_ScrRec_LabelVolume = NULL;
// event funtions
void ui_event_ScrRec_BtnExit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED)
    {
        arHandle.isDeInit = true;
        _ui_screen_change(&ui_ScrMain,&ui_ScrRec,LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrMain_screen_init);
    }
}

void ui_event_ScrRec_Btn_Play(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        scr_rec_btn_play_cb(e);
    }
}

void ui_event_ScrRec_Btn_Over(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        src_rec_btn_over_cb(e);
        _ui_label_set_property(ui_ScrRec_PrecessRecTime, _UI_LABEL_PROPERTY_TEXT, "0:00");
    }
}

void ui_event_ScrRec_Btn_Record(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        scr_rec_btn_record_cb(e);
    }
}

void ui_event_ScrRec_DialogBtnYes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        scr_rec_dialog_btn_yes(e);
        _ui_flag_modify(ui_ScrRec_ContDialog, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScrRec_DialogBtnNo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ScrRec_ContDialog, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScrRec_SliderVolume(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        scr_rec_volume_slider_cb(e);
        _ui_slider_set_text_value(ui_ScrRec_LabelVolume, target, "音量：", "");
    }
}

// build funtions

void ui_ScrRec_screen_init(void)
{
    ui_ScrRec = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrRec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_ScrRec, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_ScrRec_screen_destroy);

    ui_ScrRec_ContHeader = lv_obj_create(ui_ScrRec);
    lv_obj_remove_style_all(ui_ScrRec_ContHeader);
    lv_obj_set_width(ui_ScrRec_ContHeader, lv_pct(100));
    lv_obj_set_height(ui_ScrRec_ContHeader, lv_pct(10));
    lv_obj_remove_flag(ui_ScrRec_ContHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrRec_ContHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrRec_ContHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScrRec_ContHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrRec_ContHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrRec_ContHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScrRec_ContHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrRec_ContHeader, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ScrRec_ContHeader, lv_color_hex(0xEEEAEE), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrRec_ContHeader, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ScrRec_BtnExit = lv_button_create(ui_ScrRec_ContHeader);
    lv_obj_set_height(ui_ScrRec_BtnExit, lv_pct(100));
    lv_obj_set_width(ui_ScrRec_BtnExit, LV_SIZE_CONTENT);   /// 15
    lv_obj_add_flag(ui_ScrRec_BtnExit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrRec_BtnExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrRec_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrRec_BtnExit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrRec_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScrRec_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScrRec_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrRec_LabelExit = lv_label_create(ui_ScrRec_BtnExit);
    lv_obj_set_width(ui_ScrRec_LabelExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrRec_LabelExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrRec_LabelExit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrRec_LabelExit, LV_SYMBOL_LEFT);
    lv_obj_set_style_text_color(ui_ScrRec_LabelExit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrRec_LabelExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrRec_LabelExit, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrRec_LabelTitle = lv_label_create(ui_ScrRec_ContHeader);
    lv_obj_set_width(ui_ScrRec_LabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrRec_LabelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrRec_LabelTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrRec_LabelTitle, "录音");
    lv_obj_set_style_text_font(ui_ScrRec_LabelTitle, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrRec_ContBody = lv_obj_create(ui_ScrRec);
    lv_obj_remove_style_all(ui_ScrRec_ContBody);
    lv_obj_set_width(ui_ScrRec_ContBody, lv_pct(100));
    lv_obj_set_height(ui_ScrRec_ContBody, lv_pct(50));
    lv_obj_set_x(ui_ScrRec_ContBody, lv_pct(0));
    lv_obj_set_y(ui_ScrRec_ContBody, lv_pct(10));
    lv_obj_remove_flag(ui_ScrRec_ContBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ScrRec_ContBody, lv_color_hex(0x8E8E8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrRec_ContBody, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrRec_ContBody, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrRec_ContProcess = lv_obj_create(ui_ScrRec);
    lv_obj_remove_style_all(ui_ScrRec_ContProcess);
    lv_obj_set_width(ui_ScrRec_ContProcess, lv_pct(100));
    lv_obj_set_height(ui_ScrRec_ContProcess, lv_pct(15));
    lv_obj_set_x(ui_ScrRec_ContProcess, lv_pct(0));
    lv_obj_set_y(ui_ScrRec_ContProcess, lv_pct(70));
    lv_obj_remove_flag(ui_ScrRec_ContProcess, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ScrRec_ContProcess, lv_color_hex(0xBCBCBC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrRec_ContProcess, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrRec_ContProcess, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrRec_Process = lv_bar_create(ui_ScrRec_ContProcess);
    lv_obj_set_width(ui_ScrRec_Process, lv_pct(90));
    lv_obj_set_height(ui_ScrRec_Process, lv_pct(10));
    lv_obj_set_x(ui_ScrRec_Process, lv_pct(0));
    lv_obj_set_y(ui_ScrRec_Process, lv_pct(35));
    lv_obj_set_align(ui_ScrRec_Process, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ScrRec_Process, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ScrRec_Process,
                                                                                                     lv_obj_get_style_pad_right(ui_ScrRec_Process, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ScrRec_Process_Time = lv_label_create(ui_ScrRec_ContProcess);
    lv_obj_set_width(ui_ScrRec_Process_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrRec_Process_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrRec_Process_Time, lv_pct(6));
    lv_obj_set_y(ui_ScrRec_Process_Time, lv_pct(10));
    lv_obj_set_align(ui_ScrRec_Process_Time, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ScrRec_Process_Time, "0:00/00:00");

    ui_ScrRec_ProcessLabel = lv_label_create(ui_ScrRec_ContProcess);
    lv_obj_set_width(ui_ScrRec_ProcessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrRec_ProcessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrRec_ProcessLabel, lv_pct(5));
    lv_obj_set_y(ui_ScrRec_ProcessLabel, lv_pct(0));
    lv_label_set_text(ui_ScrRec_ProcessLabel, "");

    ui_ScrRec_PrecessRecTime = lv_label_create(ui_ScrRec_ContProcess);
    lv_obj_set_width(ui_ScrRec_PrecessRecTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrRec_PrecessRecTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrRec_PrecessRecTime, lv_pct(-10));
    lv_obj_set_y(ui_ScrRec_PrecessRecTime, lv_pct(-25));
    lv_obj_set_align(ui_ScrRec_PrecessRecTime, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_ScrRec_PrecessRecTime, "0:00");

    ui_ScrRec_ContFooter = lv_obj_create(ui_ScrRec);
    lv_obj_remove_style_all(ui_ScrRec_ContFooter);
    lv_obj_set_width(ui_ScrRec_ContFooter, lv_pct(100));
    lv_obj_set_height(ui_ScrRec_ContFooter, lv_pct(15));
    lv_obj_set_x(ui_ScrRec_ContFooter, lv_pct(0));
    lv_obj_set_y(ui_ScrRec_ContFooter, lv_pct(85));
    lv_obj_remove_flag(ui_ScrRec_ContFooter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrRec_Btn_Play = lv_button_create(ui_ScrRec_ContFooter);
    lv_obj_set_width(ui_ScrRec_Btn_Play, lv_pct(25));
    lv_obj_set_height(ui_ScrRec_Btn_Play, lv_pct(80));
    lv_obj_set_align(ui_ScrRec_Btn_Play, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScrRec_Btn_Play, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrRec_Btn_Play, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrRec_Btn_Play, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrRec_Btn_Play, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrRec_Btn_Play, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScrRec_Btn_Play, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrRec_Btn_Play, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrRec_Btn_Play, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrRec_LabelPlay = lv_label_create(ui_ScrRec_Btn_Play);
    lv_obj_set_width(ui_ScrRec_LabelPlay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrRec_LabelPlay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrRec_LabelPlay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrRec_LabelPlay, "播放");
    lv_obj_set_state(ui_ScrRec_Btn_Play, LV_STATE_DISABLED, true);
    lv_obj_set_style_text_color(ui_ScrRec_LabelPlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrRec_LabelPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrRec_Btn_Over = lv_button_create(ui_ScrRec_ContFooter);
    lv_obj_set_width(ui_ScrRec_Btn_Over, lv_pct(25));
    lv_obj_set_height(ui_ScrRec_Btn_Over, lv_pct(80));
    lv_obj_set_x(ui_ScrRec_Btn_Over, lv_pct(-5));
    lv_obj_set_y(ui_ScrRec_Btn_Over, lv_pct(0));
    lv_obj_set_align(ui_ScrRec_Btn_Over, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ScrRec_Btn_Over, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrRec_Btn_Over, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrRec_Btn_Over, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrRec_Btn_Over, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrRec_Btn_Over, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScrRec_Btn_Over, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrRec_Btn_Over, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrRec_Btn_Over, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrRec_LabelOver = lv_label_create(ui_ScrRec_Btn_Over);
    lv_obj_set_width(ui_ScrRec_LabelOver, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrRec_LabelOver, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrRec_LabelOver, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrRec_LabelOver, "结束");
    lv_obj_set_style_text_color(ui_ScrRec_LabelOver, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrRec_LabelOver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrRec_Btn_Record = lv_button_create(ui_ScrRec_ContFooter);
    lv_obj_set_width(ui_ScrRec_Btn_Record, lv_pct(25));
    lv_obj_set_height(ui_ScrRec_Btn_Record, lv_pct(80));
    lv_obj_set_x(ui_ScrRec_Btn_Record, lv_pct(5));
    lv_obj_set_y(ui_ScrRec_Btn_Record, lv_pct(0));
    lv_obj_set_align(ui_ScrRec_Btn_Record, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ScrRec_Btn_Record, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrRec_Btn_Record, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrRec_Btn_Record, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrRec_Btn_Record, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrRec_Btn_Record, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScrRec_Btn_Record, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrRec_Btn_Record, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrRec_Btn_Record, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrRec_LabelRecord = lv_label_create(ui_ScrRec_Btn_Record);
    lv_obj_set_width(ui_ScrRec_LabelRecord, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrRec_LabelRecord, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrRec_LabelRecord, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrRec_LabelRecord, "录音");
    lv_obj_set_style_text_color(ui_ScrRec_LabelRecord, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrRec_LabelRecord, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrRec_ContDialog = lv_obj_create(ui_ScrRec);
    lv_obj_remove_style_all(ui_ScrRec_ContDialog);
    lv_obj_set_width(ui_ScrRec_ContDialog, lv_pct(80));
    lv_obj_set_height(ui_ScrRec_ContDialog, lv_pct(40));
    lv_obj_set_x(ui_ScrRec_ContDialog, lv_pct(0));
    lv_obj_set_y(ui_ScrRec_ContDialog, lv_pct(-10));
    lv_obj_set_align(ui_ScrRec_ContDialog, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScrRec_ContDialog, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ScrRec_ContDialog, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrRec_ContDialog, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrRec_ContDialog, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrRec_ContDialog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScrRec_ContDialog, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScrRec_ContDialog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScrRec_ContDialog, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrRec_DialogLabelMain = lv_label_create(ui_ScrRec_ContDialog);
    lv_obj_set_width(ui_ScrRec_DialogLabelMain, lv_pct(90));
    lv_obj_set_height(ui_ScrRec_DialogLabelMain, lv_pct(50));
    lv_obj_set_x(ui_ScrRec_DialogLabelMain, lv_pct(5));
    lv_obj_set_y(ui_ScrRec_DialogLabelMain, lv_pct(10));
    lv_label_set_text(ui_ScrRec_DialogLabelMain, "Is Music XXXXXX delete");

    ui_ScrRec_DialogBtnYes = lv_button_create(ui_ScrRec_ContDialog);
    lv_obj_set_width(ui_ScrRec_DialogBtnYes, lv_pct(30));
    lv_obj_set_height(ui_ScrRec_DialogBtnYes, lv_pct(20));
    lv_obj_set_x(ui_ScrRec_DialogBtnYes, lv_pct(10));
    lv_obj_set_y(ui_ScrRec_DialogBtnYes, lv_pct(-10));
    lv_obj_set_align(ui_ScrRec_DialogBtnYes, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_ScrRec_DialogBtnYes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrRec_DialogBtnYes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrRec_DialogLabelYes = lv_label_create(ui_ScrRec_DialogBtnYes);
    lv_obj_set_width(ui_ScrRec_DialogLabelYes, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_ScrRec_DialogLabelYes, LV_SIZE_CONTENT);    /// 7
    lv_obj_set_align(ui_ScrRec_DialogLabelYes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrRec_DialogLabelYes, "Yes");
    lv_obj_set_style_text_color(ui_ScrRec_DialogLabelYes, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrRec_DialogLabelYes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrRec_DialogBtnNo = lv_button_create(ui_ScrRec_ContDialog);
    lv_obj_set_width(ui_ScrRec_DialogBtnNo, lv_pct(30));
    lv_obj_set_height(ui_ScrRec_DialogBtnNo, lv_pct(20));
    lv_obj_set_x(ui_ScrRec_DialogBtnNo, lv_pct(-10));
    lv_obj_set_y(ui_ScrRec_DialogBtnNo, lv_pct(-10));
    lv_obj_set_align(ui_ScrRec_DialogBtnNo, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_ScrRec_DialogBtnNo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrRec_DialogBtnNo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrRec_DialogLabelNo = lv_label_create(ui_ScrRec_DialogBtnNo);
    lv_obj_set_width(ui_ScrRec_DialogLabelNo, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_ScrRec_DialogLabelNo, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_ScrRec_DialogLabelNo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrRec_DialogLabelNo, "No");
    lv_obj_set_style_text_color(ui_ScrRec_DialogLabelNo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrRec_DialogLabelNo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrRec_SliderVolume = lv_slider_create(ui_ScrRec);
    lv_slider_set_value(ui_ScrRec_SliderVolume, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ScrRec_SliderVolume) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_ScrRec_SliderVolume,
                                                                                                        0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ScrRec_SliderVolume, lv_pct(60));
    lv_obj_set_height(ui_ScrRec_SliderVolume, lv_pct(1));
    lv_obj_set_x(ui_ScrRec_SliderVolume, lv_pct(10));
    lv_obj_set_y(ui_ScrRec_SliderVolume, lv_pct(15));
    lv_obj_set_align(ui_ScrRec_SliderVolume, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ScrRec_SliderVolume,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ScrRec_SliderVolume, lv_obj_get_style_pad_right(ui_ScrRec_SliderVolume,
                                                                                  LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ScrRec_LabelVolume = lv_label_create(ui_ScrRec);
    lv_obj_set_width(ui_ScrRec_LabelVolume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrRec_LabelVolume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrRec_LabelVolume, lv_pct(5));
    lv_obj_set_y(ui_ScrRec_LabelVolume, lv_pct(15));
    lv_obj_set_align(ui_ScrRec_LabelVolume, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ScrRec_LabelVolume, "音量：0");

    lv_obj_add_event_cb(ui_ScrRec_BtnExit, ui_event_ScrRec_BtnExit, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrRec_Btn_Play, ui_event_ScrRec_Btn_Play, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrRec_Btn_Over, ui_event_ScrRec_Btn_Over, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrRec_Btn_Record, ui_event_ScrRec_Btn_Record, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrRec_DialogBtnYes, ui_event_ScrRec_DialogBtnYes, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrRec_DialogBtnNo, ui_event_ScrRec_DialogBtnNo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrRec_SliderVolume, ui_event_ScrRec_SliderVolume, LV_EVENT_ALL, NULL);

    arHandle.isInit = 1;
}

void ui_ScrRec_screen_destroy(void)
{
    if(ui_ScrRec) lv_obj_del(ui_ScrRec);

    // NULL screen variables
    ui_ScrRec = NULL;
    ui_ScrRec_ContHeader = NULL;
    ui_ScrRec_BtnExit = NULL;
    ui_ScrRec_LabelExit = NULL;
    ui_ScrRec_LabelTitle = NULL;
    ui_ScrRec_ContBody = NULL;
    ui_ScrRec_ContProcess = NULL;
    ui_ScrRec_Process = NULL;
    ui_ScrRec_Process_Time = NULL;
    ui_ScrRec_ProcessLabel = NULL;
    ui_ScrRec_PrecessRecTime = NULL;
    ui_ScrRec_ContFooter = NULL;
    ui_ScrRec_Btn_Play = NULL;
    ui_ScrRec_LabelPlay = NULL;
    ui_ScrRec_Btn_Over = NULL;
    ui_ScrRec_LabelOver = NULL;
    ui_ScrRec_Btn_Record = NULL;
    ui_ScrRec_LabelRecord = NULL;
    ui_ScrRec_ContDialog = NULL;
    ui_ScrRec_DialogLabelMain = NULL;
    ui_ScrRec_DialogBtnYes = NULL;
    ui_ScrRec_DialogLabelYes = NULL;
    ui_ScrRec_DialogBtnNo = NULL;
    ui_ScrRec_DialogLabelNo = NULL;
    ui_ScrRec_SliderVolume = NULL;
    ui_ScrRec_LabelVolume = NULL;

}

void ui_ScrRec_screen_relocalize(void)
{
    // label widgets on screen

}
