// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Mobile_Phone

#ifndef UI_SCRWEATHER_H
#define UI_SCRWEATHER_H

#include"Core/main_lib.h"
#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrWeather
extern void ui_ScrWeather_screen_init(void);
extern void ui_ScrWeather_screen_destroy(void);
extern void ui_ScrWeather_screen_relocalize(void);
extern lv_obj_t * ui_ScrWeather;
extern lv_obj_t * ui_ContMain;
extern lv_obj_t * ui_ScrWeather_ContHeader;
extern void ui_event_ScrWeather_BtnExit(lv_event_t * e);
extern lv_obj_t * ui_ScrWeather_BtnExit;
extern lv_obj_t * ui_ScrWeather_LabelExit;
extern lv_obj_t * ui_ScrWeather_LabelTitle;
extern void ui_event_ScrWeather_BtnReflush(lv_event_t * e);
extern lv_obj_t * ui_ScrWeather_BtnReflush;
extern lv_obj_t * ui_ScrWeather_LabelReflush;
extern lv_obj_t * ui_ContTools;
extern void ui_event_ScrWeather_DdSelectCity(lv_event_t * e);
extern lv_obj_t * ui_ScrWeather_DdSelectCity;
extern lv_obj_t * ui_ContBody;
extern lv_obj_t * ui_PanelBody;
extern lv_obj_t * ui_ContCurWeather;
extern lv_obj_t * ui_LabelCurTemp;
extern lv_obj_t * ui_LabelTodayWeather;
extern lv_obj_t * ui_ContDaysWeather;
extern lv_obj_t * ui_ContWeatherInfo1;
extern lv_obj_t * ui_LabelDate1;
extern lv_obj_t * ui_ImgWeather1;
extern lv_obj_t * ui_LabelPrecip1;
extern lv_obj_t * ui_LabelTodayTemp1;
extern lv_obj_t * ui_ContWeatherInfo3;
extern lv_obj_t * ui_LabelDate3;
extern lv_obj_t * ui_ImgWeather3;
extern lv_obj_t * ui_LabelPrecip3;
extern lv_obj_t * ui_LabelTodayTemp3;
extern lv_obj_t * ui_ContWeatherInfo4;
extern lv_obj_t * ui_LabelDate4;
extern lv_obj_t * ui_ImgWeather4;
extern lv_obj_t * ui_LabelPrecip4;
extern lv_obj_t * ui_LabelTodayTemp4;
extern lv_obj_t * ui_ContDetailInfo;
extern lv_obj_t * ui_ContRainFall;
extern lv_obj_t * ui_ImgRainfall;
extern lv_obj_t * ui_LabelRainfall;
extern lv_obj_t * ui_ContHumidity;
extern lv_obj_t * ui_ImgHumidity;
extern lv_obj_t * ui_LabelHumidity;
extern lv_obj_t * ui_ContWind;
extern lv_obj_t * ui_ImgWind;
extern lv_obj_t * ui_LabelWind;
extern lv_obj_t * ui_ContWindSpeed;
extern lv_obj_t * ui_ImgWindSpeed;
extern lv_obj_t * ui_LabelWindSpeed;
extern lv_obj_t* ui_ScrWeather_Mask;
extern lv_obj_t* ui_ScrWeather_Spinner;
extern lv_obj_t* ui_ScrWeather_LabelResponseRes;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

