// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Mobile_Phone

#include "../ui.h"

void ui_event_comp_ContHeader_BtnExit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ContHeader = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_RELEASED) {
        //_ui_screen_change(&ui_ScrMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrMain_screen_init);
    }
}

void ui_event_comp_ContHeader_BtnReflush(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ContHeader = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_RELEASED) {
        scr_weather_btn_reflush_cb(e);
    }
}

// COMPONENT ContHeader

lv_obj_t * ui_ContHeader_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ContHeader;
    cui_ContHeader = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_ContHeader);
    lv_obj_set_width(cui_ContHeader, lv_pct(100));
    lv_obj_set_height(cui_ContHeader, lv_pct(10));
    lv_obj_remove_flag(cui_ContHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_ContHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ContHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_ContHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_ContHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_ContHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_ContHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_ContHeader, lv_color_hex(0xEEEAEE), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ContHeader, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_t * cui_BtnExit;
    cui_BtnExit = lv_button_create(cui_ContHeader);
    lv_obj_set_height(cui_BtnExit, lv_pct(100));
    lv_obj_set_width(cui_BtnExit, LV_SIZE_CONTENT);   /// 15
    lv_obj_add_flag(cui_BtnExit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_BtnExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_BtnExit, lv_color_hex(0xEEEAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_BtnExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_BtnExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LabelExit;
    cui_LabelExit = lv_label_create(cui_BtnExit);
    lv_obj_set_width(cui_LabelExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LabelExit, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelExit, "EX");
    lv_obj_set_style_text_color(cui_LabelExit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LabelExit, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LabelTitle;
    cui_LabelTitle = lv_label_create(cui_ContHeader);
    lv_obj_set_width(cui_LabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LabelTitle, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelTitle, "HangZhou");
    lv_obj_set_style_text_font(cui_LabelTitle, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_BtnReflush;
    cui_BtnReflush = lv_button_create(cui_ContHeader);
    lv_obj_set_height(cui_BtnReflush, lv_pct(100));
    lv_obj_set_width(cui_BtnReflush, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_align(cui_BtnReflush, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_BtnReflush, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_BtnReflush, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_BtnReflush, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_BtnReflush, lv_color_hex(0xEEEAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_BtnReflush, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_BtnReflush, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_BtnReflush, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LabelReflush;
    cui_LabelReflush = lv_label_create(cui_BtnReflush);
    lv_obj_set_width(cui_LabelReflush, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelReflush, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LabelReflush, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelReflush, "Re");
    lv_obj_set_style_text_color(cui_LabelReflush, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelReflush, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LabelReflush, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTHEADER_NUM);
    children[UI_COMP_CONTHEADER_CONTHEADER] = cui_ContHeader;
    children[UI_COMP_CONTHEADER_BTNEXIT] = cui_BtnExit;
    children[UI_COMP_CONTHEADER_BTNEXIT_LABELEXIT] = cui_LabelExit;
    children[UI_COMP_CONTHEADER_LABELTITLE] = cui_LabelTitle;
    children[UI_COMP_CONTHEADER_BTNREFLUSH] = cui_BtnReflush;
    children[UI_COMP_CONTHEADER_BTNREFLUSH_LABELREFLUSH] = cui_LabelReflush;
    lv_obj_add_event_cb(cui_ContHeader, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ContHeader, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_BtnExit, ui_event_comp_ContHeader_BtnExit, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_BtnReflush, ui_event_comp_ContHeader_BtnReflush, LV_EVENT_ALL, children);
    ui_comp_ContHeader_create_hook(cui_ContHeader);
    return cui_ContHeader;
}

