// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Mobile_Phone

#ifndef _UI_COMP_CONTHEADER_H
#define _UI_COMP_CONTHEADER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ContHeader
#define UI_COMP_CONTHEADER_CONTHEADER 0
#define UI_COMP_CONTHEADER_BTNEXIT 1
#define UI_COMP_CONTHEADER_BTNEXIT_LABELEXIT 2
#define UI_COMP_CONTHEADER_LABELTITLE 3
#define UI_COMP_CONTHEADER_BTNREFLUSH 4
#define UI_COMP_CONTHEADER_BTNREFLUSH_LABELREFLUSH 5
#define _UI_COMP_CONTHEADER_NUM 6
lv_obj_t * ui_ContHeader_create(lv_obj_t * comp_parent);
void ui_event_comp_ContHeader_BtnExit(lv_event_t * e);
void ui_event_comp_ContHeader_BtnReflush(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
