// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Mobile_Phone

#ifndef _MOBILE_PHONE_UI_H
#define _MOBILE_PHONE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

#include "ui_img_manager.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_ScrMain.h"
#include "screens/ui_ScrWeather.h"
#include "screens/ui_ScrMusic.h"
#include "screens/ui_ScrAI.h"
#include  "screens/ui_ScrVedio.h"
#include  "screens/ui_ScrVedioShow.h"
#include  "screens/ui_ScrAlbum.h"
#include  "screens/ui_ScrAlbumShow.h"
#include  "screens/ui_ScrFileExplorer.h"
#include  "screens/ui_ScrRec.h"

///////////////////// VARIABLES ////////////////////
#include"img_dir.h"
#include"gui_guider.h"


#include"Core/main_lib.h"
// EVENTS

extern lv_obj_t * ui____initial_actions0;


// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
