// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Mobile_Phone

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif



void scr_main_btn_setting_cb(lv_event_t * e);
void scr_main_btn_calendar_cb(lv_event_t * e);
void scr_main_btn_fe_cb(lv_event_t * e);
void scr_main_btn_album_cb(lv_event_t * e);
void scr_main_btn_vedio_cb(lv_event_t * e);
void scr_main_btn_camera_cb(lv_event_t * e);
void scr_weather_btn_reflush_cb(lv_event_t * e);
void scr_weather_dd_select_city_cb(lv_event_t * e);
void scr_music_btn_song1_cb(lv_event_t * e);
void scr_music_slider_cb(lv_event_t * e);
void scr_music_btn_play_mode_cb(lv_event_t * e);
void scr_music_btn_prev_cb(lv_event_t * e);
void scr_music_btn_play_cb(lv_event_t * e);
void scr_music_btn_next_cb(lv_event_t * e);
void scr_music_dialog_btn_yes(lv_event_t* e);
void scr_music_slider_vol1_cb(lv_event_t* e);
void scr_music_slider_vol2_cb(lv_event_t* e);
void scr_music_btn_connect(lv_event_t* e);

void scr_main_btn_ai_cb(lv_event_t* e);
void src_ai_btn_send_cb(lv_event_t* e);
void scr_ai_dropdown_event_cb(lv_event_t* e);

void scr_vedio_show_eh(lv_event_t* e);
void scr_vedio_show_btn_prev_eh(lv_event_t* e);
void scr_vedio_show_btn_play_eh(lv_event_t* e);
void scr_vedio_show_btn_next_eh(lv_event_t* e);
void scr_vedio_show_slider_eh(lv_event_t* e);
void scr_vedio_show_cont_main_eh(lv_event_t* e);
void scr_vedio_show_cont_main_eh2(lv_event_t* e);

void scr_rec_btn_play_cb(lv_event_t* e);
void src_rec_btn_over_cb(lv_event_t* e);
void scr_rec_btn_record_cb(lv_event_t* e);
void scr_rec_dialog_btn_yes(lv_event_t* e);
void scr_rec_volume_slider_cb(lv_event_t* e);



#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
