// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Mobile_Phone

#include "ui.h"
#include"UI/gui_guider.h"
#include"../Core/music.h"
#include"../Core/app_handles.h"
void BtnExit(lv_event_t * e)
{
	// Your code here
}

void ScrWeatherBtnExit(lv_event_t * e)
{
	// Your code here
}

void scr_weather_btn_exit_cb(lv_event_t * e)
{
	// Your code here
}

void scr_weather_btn_reflush_cb(lv_event_t * e)
{
	// Your code here
   
    weatherHandle.isReflush = 1;
}

void scr_weather_dd_select_city_cb(lv_event_t* e)
{
    // Your code here
    char buf[32] = { 0 };
    lv_obj_t* dropdown = lv_event_get_target_obj(e);
    lv_dropdown_get_selected_str(dropdown, buf, sizeof(buf));
    lv_label_set_text(ui_ScrWeather_LabelTitle, buf);

    weatherHandle.isReflush = 1;
}

void scr_music_slider(lv_event_t * e)
{
	// Your code here
}

void scr_music_slider_cb(lv_event_t * e)
{
	// Your code here
  

}


void scr_main_btn_setting_cb(lv_event_t* e)
{
    // Your code here
    //_ui_screen_change(&guider_ui.screen_setting, &ui_ScrMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &setup_scr_screen_setting);
    ui_ScrMain_screen_destroy();
    ui_load_scr_no_animation(&guider_ui,&guider_ui.screen_setting,true, &guider_ui.screen_main_del, setup_scr_screen_setting);
}

void scr_main_btn_calendar_cb(lv_event_t* e)
{
    // Your code here
    ui_ScrMain_screen_destroy();
    ui_load_scr_no_animation(&guider_ui, &guider_ui.screen_calendar, true, &guider_ui.screen_main_del, setup_scr_screen_calendar);
}

void scr_main_btn_fe_cb(lv_event_t* e)
{
    // Your code here
    _ui_screen_change(&ui_ScrFileExplorer, &ui_ScrMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_ScrFileExplorer_screen_init);
}

void scr_main_btn_album_cb(lv_event_t* e)
{
    // Your code here
    ui_ScrMain_screen_destroy();
    ui_load_scr_no_animation(&guider_ui, &guider_ui.screen_album, true, &guider_ui.screen_main_del, setup_scr_screen_album);
}

void scr_main_btn_vedio_cb(lv_event_t* e)
{
    // Your code here
    ui_ScrMain_screen_destroy();
    ui_load_scr_no_animation(&guider_ui, &guider_ui.screen_vedio, true, &guider_ui.screen_main_del, setup_scr_screen_vedio);
}

void scr_main_btn_camera_cb(lv_event_t* e)
{
    // Your code here
    ui_ScrMain_screen_destroy();
    ui_load_scr_no_animation(&guider_ui, &guider_ui.screen_camera, true, &guider_ui.screen_main_del, setup_scr_screen_camera);
}




void scr_music_btn_song1_cb(lv_event_t * e)
{
	// Your code here
    lv_obj_t* btn = lv_event_get_target_obj(e);
    lv_obj_t* label = lv_obj_get_child(btn, 0);
    lv_label_set_text(ui_ScrMusic_LabelSongName ,lv_label_get_text(label));
    lv_tabview_set_active(ui_ScrMusic_TabView, 1, LV_ANIM_OFF);

    /*新增12-27*/
    musicHandle.index=lv_obj_get_index(btn);
    printf("current index:%d\n", musicHandle.index);
}

void scr_music_btn_play_mode_cb(lv_event_t * e)
{
	// Your code here
    musicHandle.isClickedPlayMode = 1; /*点击了该按钮*/
}

void scr_music_btn_prev_cb(lv_event_t * e)
{
	// Your code here
    musicHandle.isPrev = 1;
}

void scr_music_btn_play_cb(lv_event_t * e)
{
	// Your code here
    musicHandle.isClickedPlay = 1;
}

void scr_music_btn_next_cb(lv_event_t * e)
{
	// Your code here
    musicHandle.isNext = 1;

}

//void scr_music_btn_volume_cb(lv_event_t * e)
//{
//	// Your code here
//    static bool isClicked = true;
//    if (isClicked) /*第一次点了后音量出来*/
//    {
//        lv_obj_clear_flag(ui_ScrMusic_ContVolume, LV_OBJ_FLAG_HIDDEN);
//    }
//    else
//    {
//        lv_obj_add_flag(ui_ScrMusic_ContVolume, LV_OBJ_FLAG_HIDDEN);
//    }
//
//    isClicked = (isClicked == true) ? false : true;
//}

void scr_music_dialog_btn_yes(lv_event_t* e)
{
    // Your code here
    musicHandle.isDelete = true;
}


void scr_music_slider_vol1_cb(lv_event_t* e)
{
    // Your code here
    musicHandle.isModifyVol = 1;
    musicHandle.vol1 = lv_bar_get_value(ui_ScrMusic_SliderVolume1);
}

void scr_music_slider_vol2_cb(lv_event_t* e)
{
    // Your code here
    musicHandle.isModifyVol = 1;
    musicHandle.vol2=lv_bar_get_value(ui_ScrMusic_SliderVolume2);
}

void scr_music_btn_connect(lv_event_t* e)
{
    // Your code here
    musicHandle.isClickedConn = true;
}





void scr_main_btn_ai_cb(lv_event_t* e)
{
    _ui_screen_change(&ui_ScrAI, &ui_ScrMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrAI_screen_init);
}




void src_ai_btn_send_cb(lv_event_t* e)
{
    // Your code here
    aiHandle.isAISend = 1;
}

void scr_ai_dropdown_event_cb(lv_event_t* e)
{
    // Your code here
    aiHandle.isSwitchAI = 1;
}




/***********scr_vedio_show 屏幕**********/

uint8_t isVerGesture = 0;
void scr_vedio_show_eh(lv_event_t* e)
{
    printf("gesture ver\n");
    lv_point_t point;
    lv_indev_get_vect(lv_indev_active(), &point);
    isVerGesture = 1;
    lv_obj_remove_flag(ui_ScrVedioShow_ContVolume, LV_OBJ_FLAG_HIDDEN);
    //lv_indev_wait_release(lv_indev_active());   
}

void scr_vedio_show_btn_prev_eh(lv_event_t* e)
{
    // Your code here
    vedioHandle.isPlayPrev = 1;
}

void scr_vedio_show_btn_play_eh(lv_event_t* e)
{
    // Your code here
    vedioHandle.isPlay++;
    if (vedioHandle.isPlay == 1) lv_label_set_text(ui_ScrVedioShow_LabelPlay, LV_SYMBOL_PLAY);
    else if (vedioHandle.isPlay == 0) lv_label_set_text(ui_ScrVedioShow_LabelPlay, LV_SYMBOL_PAUSE);
}

void scr_vedio_show_btn_next_eh(lv_event_t* e)
{
    // Your code here
    vedioHandle.isPlayNext = 1;
}

void scr_vedio_show_slider_eh(lv_event_t* e)
{
    // Your code here
    lv_obj_t* slider = lv_event_get_target_obj(e);
    vedioHandle.isSliderReleased = 1;
    printf("slider value released\n");
}

void scr_vedio_show_cont_main_eh(lv_event_t* e)
{
    isVerGesture = 0;
    lv_obj_add_flag(ui_ScrVedioShow_ContVolume, LV_OBJ_FLAG_HIDDEN);
}

void scr_vedio_show_cont_main_eh2(lv_event_t* e)
{
    //printf("pressing\n");
    if (isVerGesture == 0) return; /*没有触发手势事件*/

    lv_point_t point;
    lv_indev_get_vect(lv_indev_active(), &point); /*获取滑动的x,y向量值*/

    int8_t val = 0;
    //if (point.y >= -2 && point.y <= 2)return;  
    if (point.y == 0)return;


    /*修改音量值*/

    val = -(point.y / 2);
    int32_t curVal = lv_bar_get_value(ui_ScrVedioShow_BarVolume);
    int32_t maxVal = lv_bar_get_max_value(ui_ScrVedioShow_BarVolume);
    if (curVal + val > maxVal)
    {
        lv_bar_set_value(ui_ScrVedioShow_BarVolume, maxVal, LV_ANIM_OFF);
    }
    else if(curVal + val < 0)
    {
        lv_bar_set_value(ui_ScrVedioShow_BarVolume, 0, LV_ANIM_OFF);
    }
    else
    {
        _ui_bar_increment(ui_ScrVedioShow_BarVolume, val, LV_ANIM_OFF);
    }

    printf("vect_y=%d,curVal:%d\n",point.y, lv_bar_get_value(ui_ScrVedioShow_BarVolume));

    //scr_vedio_show_timer = lv_timer_create(scr_vedio_show_timer_cb, 500, NULL);

    //lv_indev_wait_release(lv_indev_active());   
}




void scr_rec_btn_play_cb(lv_event_t* e)
{
    // Your code here
    arHandle.isClickedPlay = true;
}

void src_rec_btn_over_cb(lv_event_t* e)
{
    // Your code here
    arHandle.status = AUDIO_STATUS_OVER;
}

void scr_rec_dialog_btn_yes(lv_event_t* e)
{
    // Your code here
    arHandle.isDelete = true;
}

void scr_rec_volume_slider_cb(lv_event_t* e)
{
    // Your code here
    arHandle.volume = lv_slider_get_value(ui_ScrRec_SliderVolume); /*获取音量*/
}

void scr_rec_btn_record_cb(lv_event_t* e)
{
    // Your code here
    arHandle.isClickedRec = true;
}
